---
title: "S02-run_sims"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{S02-run_sims}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#.libPaths("/home/n_dup/R/x86_64-pc-linux-gnu-library/4.2", include.site = FALSE)
library(rlang)
library(mgcv)
library(arrow)
library(dplyr)
library(lextremagam)
library(pracma)#for tic toc
library(gratia)
library(marginaleffects)
library(foreach) #parallelized for loop
library(parallel) #to set up cores
library(doParallel) #to register cores
library(purrr )#import data to run gams
#set up parallel processing,

#set PP loop to:
#run gam,
#run segment finder
#extract segment_summary (or just peark-trough summary?)
#extract key gam summary stats (edf, R^2?, AIC) - find a reason for these, if not, no
#stop parallel processing
#sort model variables in an organized way
#save to file (rda?)


```

```{r}
run_analyses_freq <- function(sim_data, logname, gam_type = "ad", me = TRUE, alpha = 0.05){ 
  sim_data <- sim_data
  #using the user-defined logname to set up a new parallel processing logging file
  log_file <- paste0("data-raw/sim/analysis_logs/", logname, ".txt")
  file.create(log_file)
  
  start_time <- as.numeric(Sys.time())
  
  #Parallel processing using the sim_data passed in the function
  sim_dat_detect_results_list <- foreach (i = unique(sim_data$sample_id) #iterating for each ID number
                                          )%do% {
                                            #.packages=c("rlang",'dplyr', 'lextremagam','pracma', "mgcv", "gratia" , "marginaleffects")
      cat(paste0(Sys.time(), ",Iteration Start,", "Sample ID,", i,  ",Time since foreach loop start,", as.numeric(Sys.time())-start_time, "\n" ), file=log_file, append=TRUE)
# 
#   .libPaths("/home/n_dup/R/x86_64-pc-linux-gnu-library/4.2", include.site = FALSE)
# 
#   library("rlang", lib.loc = "/home/n_dup/R/x86_64-pc-linux-gnu-library/4.2")
#   library("dplyr", lib.loc = "/home/n_dup/R/x86_64-pc-linux-gnu-library/4.2")
#   library("lextremagam", lib.loc = "/home/n_dup/R/x86_64-pc-linux-gnu-library/4.2")
#   library("pracma", lib.loc = "/home/n_dup/R/x86_64-pc-linux-gnu-library/4.2")
#   library("mgcv", lib.loc = "/home/n_dup/R/x86_64-pc-linux-gnu-library/4.2")
#   library("gratia", lib.loc = "/home/n_dup/R/x86_64-pc-linux-gnu-library/4.2")
#   library("marginaleffects", lib.loc = "/home/n_dup/R/x86_64-pc-linux-gnu-library/4.2")
                                            
#merges list output into a dataframe, where each iteration output is a row
                                            
    cat(paste0(Sys.time(), ",Packages loaded,", "Sample ID,", i,  ",Time since foreach loop start,", as.numeric(Sys.time())-start_time, "\n" ), file=log_file, append=TRUE)
     # selecting only the test data for iteration i ####
    test_data <- sim_data%>%
      dplyr::filter(sample_id==i)
    x <- test_data$x
    y <- test_data$y
    
   cat(paste0(Sys.time(), "Data subset,", "Sample ID,", i,  ",Sample size,", nrow(test_data), "\n" ), file=log_file, append=TRUE)
    
    #quadratic regression ####
    tic()
    quad_results <- lextremagam:::peaktest_quad(x=x, y=y)
    #returns a numerical value u (boolean significance) under the criteria 
    #"if (!is.na(jn1) & !is.na(jn2)) if (jn1>min(x) & jn1<max(x) & jn2>min(x) & jn2<max(x) & jn1>jn2) u=1

    # two_lines (2-1 c)  ####
    twolines_results <- lextremagam:::peaktest_twolines(x=x, y=y)
    # returns boolean u significance for 3 different rHood methods and 3lines test
    #res=c(rmax$u.sig,rmed$u.sig, rprop$u.sig,u.3lines)  
    #rmax: xc=max(yhat)
    #rmed: xc=median(yflat)- yflat defined as the range where yhat+1SE>=max(yhat)
    #rprop: uses robin hood algorithm on the rmed break point to determine a new breakpoint
    #u.3lines: uses 3-lines method (not sure beyond that...)
    time_simon <- toc()
    
    #returing a vector with all the values in the correct order
    #func will be added later based on sample ID
    peaktest_results <- data.frame( sample_id = test_data$sample_id[1], 
      scenario_id = test_data$scenario_id[1],
      func = test_data$func[1],
      param = test_data$param[1],
      rep = test_data$rep[1],
      error = test_data$error[1],
      dup = test_data$dup[1],
      quad_u = quad_results,     #quad_u
      rmax_u = twolines_results[1],   #rmax_u
      rmed_u = twolines_results[2],    #rmed_u
      rprop_u = twolines_results[3], #rprop_u
      lines3_u = twolines_results[4]) #lines3_u

        cat(paste0(Sys.time(), 
                   ",Simonsohn analyses complete,", "Sample ID,", i,  ",Duration of Simon analyses,", time_simon, "\n" ),
        file=log_file, append=TRUE)
    
    #quantify local extrema
      #fit gam
      tic()
      cat(paste0(Sys.time(),  ", Just before running gam", "\n" ), 
          file=log_file, append=TRUE)
  
    if(gam_type == "ad"){  
      sim_gam <- gam(y ~ s(x, bs="ad", m=3), 
                           method = "REML", 
                           data = test_data)
    }else if (gam_type == "tprs"){
      sim_gam <- gam(y ~ s(x), 
                           method = "REML", 
                           data = test_data)
    }
                    cat(paste0(Sys.time(), 
                   ",", i, ", Gam ran. Gam object size: ", length(sim_gam), "\n" ),
        file=log_file, append=TRUE)
                    
    summary_sim_gam <- summary(sim_gam)
    
      sim_gam_params <- as.data.frame(cbind(i,
                              sim_gam$aic, 
                              sim_gam$converged,
                              sim_gam$outer.info$iter,
                              summary_sim_gam$residual.df,
                              summary_sim_gam$chi.sq,
                              summary_sim_gam$r.sq,
                              summary_sim_gam$s.table[[4]],#Smooth p-value
                              summary_sim_gam$edf,    #edf
                              summary_sim_gam$dev.expl)) #deviance explained) 
      names(sim_gam_params) <- c("sample_id", "aic", "converged", "n_iter", "residual_df", "chis_sq", "r_sq_adj", "p_smooth", "edf", "dev_expl")
    
     cat(paste0(Sys.time(), ",", i, ", Params grouped: number of columns", ncol(sim_gam_params), "\n" ),
        file=log_file, append=TRUE)
          
    #Finding lextrema
      #with marginaleffects

      if (me){
        lextrema_summary_me <- lextremagam::quantify_lextrema(mod = sim_gam,
                                             var = "x",
                                             step_size = 0.0005,
                                             conf_level = 1-alpha,
                                             deriv_method = "marginaleffects",
                                             frequentist = TRUE)
      } else {
        lextrema_summary_me <- NULL
      }
      
       cat(paste0(Sys.time(),  ",", i, ", quantify_lextrema_ran_me", length(lextrema_summary_me), "\n" ),
        file=log_file, append=TRUE)
                
      lextrema_summary_me$segment_summary$sample_id <- i
      
      #with gratia
      lextrema_summary_gr <- lextremagam::quantify_lextrema(mod = sim_gam,
                                           var = "x", 
                                           step_size = 0.0005, 
                                           conf_level = 1-alpha,
                                           deriv_method = "gratia",
                                           frequentist = TRUE) 
      
       cat(paste0(Sys.time(),  ",", i, ", quantify_lextrema_ran_gr", length(lextrema_summary_gr), "\n" ),
        file=log_file, append=TRUE)
                
      lextrema_summary_gr$segment_summary$sample_id <- i
            
      time_lextrema <- toc()
      
      cat(paste0(Sys.time(),",lextrema analysis complete,", "Sample ID,", i,  ",Duration of lextrema analysis,", time_lextrema, "\n" ),
        file=log_file, append=TRUE)
              
    results <- list(sample_id = i, 
                    peaktest_results = peaktest_results,
                    gam_params = sim_gam_params, 
                    lextrema_results_me = lextrema_summary_me$segment_summary,
                    lextrema_results_gr = lextrema_summary_gr$segment_summary)
    #returing concatenated analysis results for sample ID=i
    gc()
    return(results)
  }

  #rowbinding all peaktest_results
      peaktest_results_list <- map(sim_dat_detect_results_list, ~ .x$peaktest_results)
      peaktest_results <- do.call(rbind, peaktest_results_list)
      
  #rowbinding all lextrema results
      lextrema_results_list_me <- map(sim_dat_detect_results_list, ~ .x$lextrema_results_me)
      lextrema_results_me <- do.call(rbind, lextrema_results_list_me)
      
      lextrema_results_list_gr <- map(sim_dat_detect_results_list, ~ .x$lextrema_results_gr)
      lextrema_results_gr <- do.call(rbind, lextrema_results_list_gr)
      
  #rowbinding all gam parameters
      gam_params_list <- map(sim_dat_detect_results_list, ~ .x$gam_params)
      gam_params <- do.call(rbind, gam_params_list)
      
  results_list <- list(peaktest_results = peaktest_results,
                       lextrema_results_me = lextrema_results_me,
                       lextrema_results_gr = lextrema_results_gr,
                       gam_params = gam_params)
  
  #returing results for all samples in sim_data passed through the function
  return(results_list)
}
```

##Experiment 1
```{r}
# import data
setwd("~/Documents/Pedersen2023/Peaks/lextremagam")
sim_dat_e1 <- read_parquet(file = "data-raw/sim/data/sim_dat_e1.parquet")
sim_dat_e1 <- filter(sim_dat_e1, func == "norm")

for( i in unique(sim_dat_e1$scenario_id)){
  print(i)
  sim_dat_e1_i <- filter(sim_dat_e1, scenario_id==i)
  logname <- paste0("sim_dat_e1_freq_tprs", i, "_log")
  start_e1 <- Sys.time()
  sim_e1_i_results <- run_analyses_freq(sim_data = sim_dat_e1_i, logname = logname, me = FALSE, gam_type = "tprs")

  saveRDS(object = sim_e1_i_results, file = paste0("data-raw/sim/results/freq/e1_freq_tprs", i, "_results.RDS"))
  end_e1 <- Sys.time()
  print(end_e1-start_e1)

}

for( i in unique(sim_dat_e1$scenario_id)){
  print(i)
  sim_dat_e1_i <- filter(sim_dat_e1, scenario_id==i)
  logname <- paste0("sim_dat_e1_freq_ad", i, "_log")
  start_e1 <- Sys.time()
  sim_e1_i_results <- run_analyses_freq(sim_data = sim_dat_e1_i, logname = logname, me = FALSE, gam_type = "ad")

  saveRDS(object = sim_e1_i_results, file = paste0("data-raw/sim/results/freq/e1_freq_ad", i, "_results.RDS"))
  end_e1 <- Sys.time()
  print(end_e1-start_e1)
  
}

#lextrema_results_freq <- left_join(sim_e1_results$lextrema_results_gr, summarize(group_by(sim_dat_e1, func, param, rep, error, dup, sample_id, scenario_id), n=n()), by = "sample_id")

all_freq_names <- list.files(path = "data-raw/sim/results/freq/", full.names = TRUE)
all_freq_names_ad <- all_freq_names[1:5]
all_freq_names_tprs <- all_freq_names[6:10]

all_freq_ad <- lapply(all_freq_names_ad, readRDS)
all_freq_tprs <- lapply(all_freq_names_tprs, readRDS)

peaktest_results_freq_ad <- bind_rows(map(all_freq_ad, "peaktest_results"))
peaktest_results_freq_tprs <- bind_rows(map(all_freq_tprs, "peaktest_results"))

lextrema_results_gr_freq_ad <- bind_rows(map(all_freq_ad, "lextrema_results_gr"))
lextrema_results_gr_freq_tprs <- bind_rows(map(all_freq_tprs, "lextrema_results_gr"))

gam_params_freq_ad <- bind_rows(map(all_freq_ad, "gam_params"))
gam_params_freq_tprs <- bind_rows(map(all_freq_tprs, "gam_params"))

write_parquet(x = peaktest_results_freq_ad, sink = "data-raw/sim/results/freq/peaktest_results_e1_freq_ad.parquet")
write_parquet(x = peaktest_results_freq_tprs, sink = "data-raw/sim/results/freq/peaktest_results_e1_freq_tprs.parquet")

write_parquet(x = lextrema_results_gr_freq_ad, sink = "data-raw/sim/results/freq/lextrema_results_gr_e1_freq_ad.parquet")
write_parquet(x = lextrema_results_gr_freq_tprs, sink = "data-raw/sim/results/freq/lextrema_results_gr_e1_freq_tprs.parquet")

write_parquet(x = gam_params_freq_ad, sink = "data-raw/sim/results/freq/gam_params_e1_freq_ad.parquet")
write_parquet(x = gam_params_freq_tprs, sink = "data-raw/sim/results/freq/gam_params_e1_freq_tprs.parquet")


```

#getting the results. For this chunk, load the function in script S03
```{r}

if(!exists("ref_metadata_e1")){
sim_dat_e1 <- read_parquet("data-raw/sim/data/sim_dat_e1.parquet")
  #adding reference data
  ref_metadata_e1 <- sim_dat_e1%>%
    group_by(func, param, rep, error, dup, scenario_id)%>%
    summarize(sample_id=first(sample_id))%>%
        mutate(peak = case_when(func=="norm"~param,
                            func == "linear"~NA))%>%
    ungroup()
}

#Adaptive splines
e1_peaktest_results_freq_ad <- read_parquet("data-raw/sim/results/freq/peaktest_results_e1_freq_ad.parquet")
#e1_peaktest_results_freq_ad <- full_join(ref_metadata_e1, e1_peaktest_results_freq_ad, by="sample_id")

e1_lextrema_results_gr_freq_ad <- read_parquet("data-raw/sim/results/freq/lextrema_results_gr_e1_freq_ad.parquet")
e1_lextrema_results_gr_freq_ad <- full_join(ref_metadata_e1, e1_lextrema_results_gr_freq_ad, by="sample_id")

e1_gam_params_freq_ad <- read_parquet("data-raw/sim/results/freq/gam_params_e1_freq_ad.parquet")
e1_gam_params_freq_ad <- full_join(ref_metadata_e1, e1_gam_params_freq_ad, by="sample_id")


e1_summary_freq_ad <- get_results(peak_test = e1_peaktest_results_freq_ad,
                          lextr_me =e1_lextrema_results_gr_freq_ad, 
                          lextr_gr =  e1_lextrema_results_gr_freq_ad, 
                          gam_params = e1_gam_params_freq_ad, 
                          func_type_p = "norm", 
                          func_type_np = "linear",
                          me = FALSE)
saveRDS(e1_summary_freq_ad, "data-raw/sim/analy_results/e1_summary_ad_freq.RDS")


#Thin-plate splines
e1_peaktest_results_freq_tprs <- read_parquet("data-raw/sim/results/freq/peaktest_results_e1_freq_tprs.parquet")
#e1_peaktest_results_freq_tprs <- full_join(ref_metadata_e1, e1_peaktest_results_freq_tprs, by="sample_id")

e1_lextrema_results_gr_freq_tprs <- read_parquet("data-raw/sim/results/freq/lextrema_results_gr_e1_freq_tprs.parquet")
e1_lextrema_results_gr_freq_tprs <- full_join(ref_metadata_e1, e1_lextrema_results_gr_freq_tprs, by="sample_id")

e1_gam_params_freq_tprs <- read_parquet("data-raw/sim/results/freq/gam_params_e1_freq_tprs.parquet")
e1_gam_params_freq_tprs <- full_join(ref_metadata_e1, e1_gam_params_freq_tprs, by="sample_id")


e1_summary_freq_tprs <- get_results(peak_test = e1_peaktest_results_freq_tprs,
                          lextr_me =e1_lextrema_results_gr_freq_tprs, 
                          lextr_gr =  e1_lextrema_results_gr_freq_tprs, 
                          gam_params = e1_gam_params_freq_tprs, 
                          func_type_p = "norm", 
                          func_type_np = "linear",
                          me = FALSE)

saveRDS(e1_summary_freq_tprs, "data-raw/sim/analy_results/e1_summary_tprs_freq.RDS")
```

```{r}
# capture_gr <- lextrema_results_freq%>%
#     filter(func %in% "norm")%>%
#     rowwise()%>%
#     mutate(capture = case_when(
#       feature %in% c("local_max", "boundary_max", "notrend") ~ (peak>=x_start & peak<=x_end),
#       !( feature %in% c("local_max", "boundary_max", "notrend"))~ 0))%>%
#     ungroup()
#    
# coverage_gr <- capture_gr %>%
#     group_by(scenario_id, func, param, error, dup, sample_id, peak)%>%
#     summarize(capture = sum(capture))%>%
#     ungroup()%>%
#     group_by(scenario_id, func, param, error, dup, peak)%>%
#     summarize(coverage_gr = sum(capture)/n(),
#               n_gr = n())%>%
#     ungroup()
#    
# coverage_gr_max <- capture_gr %>%
#     filter(feature != "notrend")%>%
#     group_by(scenario_id, func, param, error, dup, sample_id)%>%
#     summarize(capture = sum(capture))%>%
#     ungroup()%>%
#     group_by(scenario_id, func, param, error, dup)%>%
#     summarize(coverage_gr_max = sum(capture)/n(),
#               n_gr_max = n())%>%
#     ungroup()
#   
# coverage <- coverage_gr%>%
#     left_join( coverage_gr_max, by=c("scenario_id", "func", "param", "error", "dup"))
```

```{r}
```

```{r}
```
