---
title: "S03-analyze_sims"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{S03-analyze_sims}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(lextremagam)
library(arrow)
library(dplyr)
library(ggplot2)
```

#functions
```{r}
get_results <- function(peak_test, lextr_me, lextr_gr, gam_params, func_type_p = NULL, func_type_np = NULL, me = TRUE){
  
  if(!me){
    lextr_me <- NULL
  }
  results <- list()
  results$power <- get_power(peak_test = peak_test, lextr_me = lextr_me, lextr_gr = lextr_gr, func_type = func_type_p, me = me)
  results$fperror <-  get_fperror(peak_test = peak_test, lextr_me = lextr_me, lextr_gr = lextr_gr, func_type = func_type_np, me= me)
  results$coverage <- get_coverage(lextr_me = lextr_me, lextr_gr = lextr_gr, func_type = func_type_p, me= me)
  results$precision <- get_precision(lextr_me = lextr_me, lextr_gr = lextr_gr, func_type = func_type_p, me= me)
  results$bias <- get_bias(lextr_me = lextr_me, lextr_gr = lextr_gr, func_type = func_type_p, me = me)
  results$anomalies <- get_weirdos(peak_test = peak_test, lextr_me = lextr_me, lextr_gr = lextr_gr, gam_params = gam_params, func_type = c(func_type_p, func_type_np), me= me)
  
  return(results)
}

get_power <- function(peak_test, lextr_me, lextr_gr, func_type, me = TRUE){
  peak_test <-  peak_test
  
  if(me){
      lextr_me <- lextr_me
  }else{
    lextr_me <- NULL
  }
  
  lextr_gr <- lextr_gr
  func_type <- func_type
  peak_test_pr <- peak_test%>%
    filter(func %in% func_type)%>%
    group_by(scenario_id, func, param, error, dup)%>%
    summarize(quad = sum(quad_u==1)/n(),
              rmax = sum(rmax_u==1)/n(),
              rmed = sum(rmed_u==1)/n(),
              rprop = sum(rprop_u==1)/n(),
              lines3 = sum(lines3_u==1)/n())%>%
    ungroup()
  
  if(me){
  lextr_me_pr <-  lextr_me%>%
    filter(func%in% func_type)%>%
    group_by(scenario_id, func, param, rep, error, dup, sample_id, peak)%>%
    summarize(me = any(feature == "local_max"))%>%
    ungroup()%>%
    group_by(scenario_id, func, param, error, dup, peak)%>%
    summarize(pr_me = sum(me)/n(),
              n_me=n())%>%
    ungroup()
  } else {
    lextr_me_pr <- NULL
  }
  
  lextr_gr_pr <-  lextr_gr%>%
    filter(func%in% func_type)%>%
    group_by(scenario_id, func, param, rep, error, dup, sample_id, peak)%>%
    summarize(gr = any(feature == "local_max"))%>%
    ungroup()%>%
    group_by(scenario_id, func, param, error, dup, peak)%>%
    summarize(pr_gr = sum(gr, na.rm = TRUE)/n(),
              n_gr=n())%>%
    ungroup()
  
  power <- peak_test_pr
  power <- left_join(power, lextr_gr_pr, by=c("scenario_id", "func", "param", "error", "dup"))
  if(me){
    power <- left_join(power, lextr_me_pr, by=c("scenario_id", "func", "param", "error", "dup", "peak"))
  }

  return(power)
}

get_fperror <- function(peak_test, lextr_me, lextr_gr, func_type, me = TRUE){
  peak_test_fp <- peak_test%>%
    filter(func %in% func_type)%>%
    group_by(scenario_id, func, param, error, dup)%>%
    summarize(quad = sum(quad_u==1)/n(),
              rmax = sum(rmax_u==1)/n(),
              rmed = sum(rmed_u==1)/n(),
              rprop = sum(rprop_u==1)/n(),
              lines3 = sum(lines3_u==1)/n())%>%
    ungroup()
  
  if(me){
    lextr_me_fp <-  lextr_me%>%
      filter(func%in% func_type)%>%
      group_by(scenario_id, func, param, rep, error, dup, sample_id)%>%
      summarize(me = any(feature == "local_max"))%>%
      ungroup()%>%
      group_by(scenario_id, func, param, error, dup)%>%
      summarize(pr_me = sum(me)/n(),
                n_me=n())%>%
      ungroup()
  }
  
  lextr_gr_fp <-  lextr_gr%>%
    filter(func%in% func_type)%>%
    group_by(scenario_id, func, param, rep, error, dup, sample_id)%>%
    summarize(gr = any(feature == "local_max"))%>%
    ungroup()%>%
    group_by(scenario_id, func, param, error, dup )%>%
    summarize(pr_gr = sum(gr, na.rm = TRUE)/n(),
              n_gr=n())%>%
    ungroup()
  
  fp_error <- peak_test_fp
  if(me){
    fp_error <- left_join(fp_error, lextr_me_fp, by=c("scenario_id", "func", "param", "error", "dup"))
  }
  fp_error <- left_join(fp_error, lextr_gr_fp, by=c("scenario_id", "func", "param", "error", "dup"))

  return(fp_error)
}

get_coverage <- function(lextr_me, lextr_gr, func_type, me = TRUE){
  if(me){
    capture_me <- lextr_me%>%
      filter(func %in% func_type)%>%
      rowwise()%>%
      mutate(capture = case_when(
        feature %in% c("local_max", "boundary_max", "notrend") ~ (peak>=x_start & peak<=x_end),
        !( feature %in% c("local_max", "boundary_max", "notrend"))~ 0))%>%
      ungroup()
    
    coverage_me <- capture_me %>%
      group_by(scenario_id, func, param, error, dup, sample_id, peak)%>%
      summarize(capture = sum(capture))%>%
      ungroup()%>%
      group_by(scenario_id, func, param, error, dup, peak)%>%
      summarize(coverage_me = sum(capture)/n(),
                n_me = n())%>%
      ungroup()
    
    coverage_me_max <- capture_me %>%
      filter(feature != "notrend")%>%
      group_by(scenario_id, func, param, error, dup, sample_id)%>%
      summarize(capture = sum(capture))%>%
      ungroup()%>%
      group_by(scenario_id, func, param, error, dup)%>%
      summarize(coverage_me_max = sum(capture)/n(),
                n_me_max = n())%>%
      ungroup()
  }
  
   capture_gr <- lextr_gr%>%
    filter(func %in% func_type)%>%
    rowwise()%>%
    mutate(capture = case_when(
      feature %in% c("local_max", "boundary_max", "notrend") ~ (peak>=x_start & peak<=x_end),
      !( feature %in% c("local_max", "boundary_max", "notrend"))~ 0))%>%
    ungroup()
   
   coverage_gr <- capture_gr %>%
    group_by(scenario_id, func, param, error, dup, sample_id, peak)%>%
    summarize(capture = sum(capture))%>%
    ungroup()%>%
    group_by(scenario_id, func, param, error, dup, peak)%>%
    summarize(coverage_gr = sum(capture)/n(),
              n_gr = n())%>%
    ungroup()
   
  coverage_gr_max <- capture_gr %>%
    filter(feature != "notrend")%>%
    group_by(scenario_id, func, param, error, dup, sample_id)%>%
    summarize(capture = sum(capture))%>%
    ungroup()%>%
    group_by(scenario_id, func, param, error, dup)%>%
    summarize(coverage_gr_max = sum(capture)/n(),
              n_gr_max = n())%>%
    ungroup()
  
  coverage <- coverage_gr%>%
    left_join( coverage_gr_max, by=c("scenario_id", "func", "param", "error", "dup"))
  if(me){
  coverage <- coverage%>%
    left_join( coverage_me, by=c("scenario_id", "func", "param", "error", "dup", "peak"))%>%
    left_join( coverage_me_max, by=c("scenario_id", "func", "param", "error", "dup"))
  }
  
  return(coverage)
}

get_precision <- function(lextr_me, lextr_gr, func_type, me = TRUE){
  if(me){
    precision_me <- lextr_me%>%
    filter(func %in% func_type, feature==c("local_max"))%>%
    mutate(width= x_end-x_start)%>%
    group_by(func, param, rep, error, dup, scenario_id, sample_id, peak)%>%
    summarize(sum_width= sum(width),
              n_seg = n())%>%
    ungroup()%>%
    group_by(func, param, error, dup, scenario_id, peak)%>%
    summarize(width_avg_me = mean(sum_width),
              width_sd_me = sd(sum_width),
              n_2etseg_me = sum(n_seg>=2),
              n_me=n())%>%
    ungroup()
  }
  
  precision_gr <- lextr_gr%>%
    filter(func %in% func_type, feature==c("local_max"))%>%
    mutate(width= x_end-x_start)%>%
    group_by(func, param, rep, error, dup, scenario_id, sample_id, peak)%>%
    summarize(sum_width= sum(width),
              n_seg = n())%>%
    ungroup()%>%
    group_by(func, param, error, dup, scenario_id, peak)%>%
    summarize(width_avg_gr = mean(sum_width),
              width_sd_gr = sd(sum_width),
              n_2etseg_gr = sum(n_seg>=2),
              n_gr=n())%>%
    ungroup()
  
  if(me){
    precision <- left_join(precision_me, precision_gr, by=c("scenario_id", "func", "param", "error", "dup", "peak"))
  } else {
    precision <- precision_gr
  }
  
  return(precision)
}

get_bias <- function(lextr_me, lextr_gr, func_type, me = TRUE){
  if(me){
    bias_me <- lextr_me%>%
      filter(feature %in% c("local_max", "boundary_max", "notrend"))%>%
      mutate(pu_dist = peak - x_end,
             pl_dist = peak - x_start)%>%
      mutate(bias = case_when(
        pu_dist<0 & pl_dist>0 ~0,
        pu_dist<0 & pl_dist<0 ~ pl_dist,
        pu_dist>0 & pl_dist>0 ~pu_dist))%>%
      group_by(func, param ,rep, error, dup, scenario_id, sample_id, peak)%>%
      summarize( n_int_me = n(), 
                 bias = sum(bias, na.rm = TRUE))%>%
      ungroup()%>%
      group_by(func, param, error, dup, scenario_id, peak)%>%
      summarize(bias_avg_me = mean(bias),
                bias_sd_me = sd(bias),
                n_me = n())%>%
      ungroup()
    
    bias_me_max <- lextr_me%>%
      filter(feature %in% c("local_max", "boundary_max"))%>%
      mutate(pu_dist = peak- x_end,
             pl_dist = peak - x_start)%>%
      mutate(bias = case_when(
        pu_dist<0 & pl_dist>0 ~0,
        pu_dist<0 & pl_dist<0 ~ pl_dist,
        pu_dist>0 & pl_dist>0 ~pu_dist))%>%
      group_by(func, param ,rep, error, dup, scenario_id, sample_id, peak)%>%
      summarize( n_int_me = n(), 
                 bias = sum(bias, na.rm = TRUE))%>%
      ungroup()%>%
      group_by(func, param, error, dup, scenario_id, peak)%>%
      summarize(bias_avg_me_max = mean(bias),
                bias_sd_me_max = sd(bias),
                n_me_max = n())%>%
      ungroup()
  }
  
  bias_gr <- lextr_gr%>%
    filter(feature %in% c("local_max", "boundary_max", "notrend"))%>%
    mutate(pu_dist = peak - x_end,
           pl_dist = peak - x_start)%>%
    mutate(bias = case_when(
      pu_dist<0 & pl_dist>0 ~0,
      pu_dist<0 & pl_dist<0 ~ pl_dist,
      pu_dist>0 & pl_dist>0 ~pu_dist))%>%
      group_by(func, param ,rep, error, dup, scenario_id, sample_id, peak)%>%
      summarize( n_int_me = n(), 
                 bias = sum(bias, na.rm = TRUE))%>%
      ungroup()%>%
      group_by(func, param, error, dup, scenario_id, peak)%>%
      summarize(bias_avg_gr = mean(bias),
                bias_sd_gr = sd(bias),
                n_gr = n())%>%
      ungroup()
  
  bias_gr_max <- lextr_gr%>%
    filter(feature %in% c("local_max", "boundary_max"))%>%
    mutate(pu_dist = peak- x_end,
           pl_dist = peak - x_start)%>%
    mutate(bias = case_when(
      pu_dist<0 & pl_dist>0 ~0,
      pu_dist<0 & pl_dist<0 ~ pl_dist,
      pu_dist>0 & pl_dist>0 ~ pu_dist))%>%
      group_by(func, param ,rep, error, dup, scenario_id, sample_id, peak)%>%
      summarize( n_int_me = n(), 
                 bias = sum(bias, na.rm = TRUE))%>%
      ungroup()%>%
      group_by(func, param, error, dup, scenario_id, peak)%>%
      summarize(bias_avg_gr_max = mean(bias),
                bias_sd_gr_max = sd(bias),
                n_gr_max = n())%>%
      ungroup()
  
  bias <- bias_gr%>%
    left_join( bias_gr_max, by=c("scenario_id", "func", "param", "error", "dup", "peak"))
  if(me){
    bias <- bias%>%
      left_join(bias_me, by=c("scenario_id", "func", "param", "error", "dup", "peak"))%>%
      left_join(bias_me_max, by=c("scenario_id", "func", "param", "error", "dup", "peak"))
  }
  
  return(bias)
}

get_bias2 <- function(lextr_me, lextr_gr, func_type, me = FALSE){
  if(me){
    bias_me <- lextr_me%>%
      dplyr::filter(feature %in% c("local_max"))%>%
      mutate(midpoint = (x_end+x_start)/2)%>%
      mutate(dist = peak-midpoint)%>%
      group_by(func, param ,rep, error, dup, scenario_id, sample_id, peak)%>%
      summarize( n_int_me = n(), 
                 dist = sum(dist, na.rm = TRUE))%>%
      ungroup()%>%
      group_by(func, param, error, dup, scenario_id, peak)%>%
      summarize(dist_avg_me = mean(dist),
                dist_sd_me = sd(dist),
                n_me = n())%>%
      ungroup()
    
    bias_me_max <- lextr_me%>%
      filter(feature %in% c("local_max", "boundary_max"))%>%
      mutate(midpoint = (x_end+x_start)/2)%>%
      mutate(dist = peak-midpoint)%>%
      group_by(func, param ,rep, error, dup, scenario_id, sample_id, peak)%>%
      summarize( n_int_me = n(), 
                 dist = sum(dist, na.rm = TRUE))%>%
      ungroup()%>%
      group_by(func, param, error, dup, scenario_id, peak)%>%
      summarize(dist_avg_me_max = mean(dist),
                dist_sd_me_max = sd(dist),
                n_me_max = n())%>%
      ungroup()
  }
  
  bias_gr <- lextr_gr%>%
    filter(feature %in% c("local_max", "boundary_max", "notrend"))%>%
    mutate(midpoint = (x_end+x_start)/2)%>%
      mutate(dist = peak-midpoint)%>%
      group_by(func, param ,rep, error, dup, scenario_id, sample_id, peak)%>%
      summarize( n_int_me = n(), 
                 dist = sum(dist, na.rm = TRUE))%>%
      ungroup()%>%
      group_by(func, param, error, dup, scenario_id, peak)%>%
      summarize(dist_avg_gr = mean(dist),
                dist_sd_gr = sd(dist),
                n_gr = n())%>%
      ungroup()
  
  bias_gr_max <- lextr_gr%>%
    filter(feature %in% c("local_max", "boundary_max"))%>%
      mutate(midpoint = (x_end+x_start)/2)%>%
      mutate(dist = peak-midpoint)%>%
      group_by(func, param ,rep, error, dup, scenario_id, sample_id, peak)%>%
      summarize( n_int_me = n(), 
                 dist = sum(dist, na.rm = TRUE))%>%
      ungroup()%>%
      group_by(func, param, error, dup, scenario_id, peak)%>%
      summarize(bias_avg_gr_max = mean(dist),
                bias_sd_gr_max = sd(dist),
                n_gr_max = n())%>%
      ungroup()
  
  bias <- bias_gr%>%
    left_join( bias_gr_max, by=c("scenario_id", "func", "param", "error", "dup", "peak"))
  if(me){
    bias <- bias%>%
      left_join(bias_me, by=c("scenario_id", "func", "param", "error", "dup", "peak"))%>%
      left_join(bias_me_max, by=c("scenario_id", "func", "param", "error", "dup", "peak"))
  }
  
  return(bias)
}

get_weirdos <- function(peak_test, lextr_me, lextr_gr, gam_params, func_type, me = TRUE){
  # samples with more that one extremeum
  if(me){
    n_extrem_me <- lextr_me %>%
      group_by(sample_id)%>%
      summarize(n_extrem = sum( feature %in% c("local_min", "local_max")))%>%
      ungroup()%>%
      filter(n_extrem>=3)%>%
      mutate(method = "me")
  }
  n_extrem_gr <- lextr_gr %>%
    group_by(sample_id)%>%
    summarize(n_extrem = sum( feature %in% c("local_min", "local_max")))%>%
    ungroup()%>%
    filter(n_extrem>=3)%>%
    mutate(method = "gr")
  
  if(me){
    many_extrema <- bind_rows(n_extrem_me, n_extrem_gr)
  }else{
    many_extrema <- n_extrem_gr
  }

  high_edf <- gam_params$sample_id[which(gam_params$edf>=6)]
  high_rsq <- gam_params$sample_id[which(gam_params$r_sq_adj>0.75)]
  
  weirdos <- list(many_extrema = many_extrema, 
                  high_edf = high_edf, 
                  high_rsq = high_rsq)
  return(weirdos)
}

```

##Experiment 1
```{r}
setwd("~/Documents/Pedersen2023/Peaks/lextremagam")
if(!exists("ref_metadata_e1")){
  sim_dat_e1 <- read_parquet("data-raw/sim/data/sim_dat_e1.parquet")
  #adding reference data
  ref_metadata_e1 <- sim_dat_e1%>%
    group_by(func, param, rep, error, dup, scenario_id)%>%
    summarize(sample_id=first(sample_id))%>%
    mutate(peak = case_when(func=="norm"~param,
                            func == "linear"~NA))%>%
    ungroup()
}

e1_gam_params <- read_parquet("data-raw/sim/results/gam_params_e1.parquet")
e1_gam_params <- full_join(ref_metadata_e1, e1_gam_params, by="sample_id")

e1_lextrema_results_me <- read_parquet("data-raw/sim/results/lextrema_results_me_e1.parquet")
e1_lextrema_results_me <- full_join(ref_metadata_e1, e1_lextrema_results_me, by="sample_id")

e1_lextrema_results_gratia <- read_parquet("data-raw/sim/results/lextrema_results_gr_e1.parquet")
e1_lextrema_results_gratia <- full_join(ref_metadata_e1, e1_lextrema_results_gratia, by="sample_id")

e1_peaktest_results <- read_parquet("data-raw/sim/results/peaktest_results_e1.parquet")
 
e1_summary <- get_results(peak_test = e1_peaktest_results,
                          lextr_me =e1_lextrema_results_me, 
                          lextr_gr =  e1_lextrema_results_gratia, 
                          gam_params = e1_gam_params, 
                          func_type_p = "norm", 
                          func_type_np = "linear", 
                          me = TRUE)

saveRDS(object = e1_summary, file = "data-raw/sim/analy_results/e1_summary.RDS")

```
##Experiment 2
```{r}
setwd("~/Documents/Pedersen2023/Peaks/lextremagam")

if(!exists("ref_metadata_e2")){
  sim_dat_e2 <- read_parquet("data-raw/sim/data/sim_dat_e2.parquet")
  #adding reference data
  ref_metadata_e2 <- sim_dat_e2%>%
    group_by(func, param, rep, error, dup, scenario_id)%>%
    summarize(sample_id=first(sample_id))%>%
    mutate(peak = case_when(func=="norm"~param,
                            func == "linear"~NA))%>%
    ungroup()
}
e2_gam_params <- read_parquet("data-raw/sim/results/gam_params_e2.parquet")
e2_gam_params <- full_join(ref_metadata_e2, e2_gam_params, by="sample_id")

e2_lextrema_results_me <- read_parquet("data-raw/sim/results/lextrema_results_me_e2.parquet")
e2_lextrema_results_me <- full_join(ref_metadata_e2, e2_lextrema_results_me, by="sample_id")
e2_lextrema_results_me$feature[which(is.na(e2_lextrema_results_me$feature))] <- "notrend"

e2_lextrema_results_gratia <- read_parquet("data-raw/sim/results/lextrema_results_gr_e2.parquet")
e2_lextrema_results_gratia <- full_join(ref_metadata_e2, e2_lextrema_results_gratia, by="sample_id")
e2_lextrema_results_gratia$feature[which(is.na(e2_lextrema_results_gratia$feature))] <- "notrend"

e2_peaktest_results <- read_parquet("data-raw/sim/results/peaktest_results_e2.parquet")
 
e2_summary <- get_results(peak_test = e2_peaktest_results,
                          lextr_me =e2_lextrema_results_me, 
                          lextr_gr =  e2_lextrema_results_gratia, 
                          gam_params = e2_gam_params, 
                          func_type_p = "norm", 
                          func_type_np = "linear", 
                          me = TRUE)

saveRDS(object = e2_summary, file = "data-raw/sim/analy_results/e2_summary.RDS")
```
#Experiment 3 ####
```{r}
setwd("~/Documents/Pedersen2023/Peaks/lextremagam")

if(!exists("ref_metadata_e3")){
  sim_dat_e3 <- read_parquet("data-raw/sim/data/sim_dat_e3.parquet")
  #adding reference data
  ref_metadata_e3 <- sim_dat_e3%>%
    group_by(func, param, rep, error, dup, scenario_id)%>%
    summarize(sample_id=first(sample_id))%>%
    mutate(peak = case_when(func == "var-p-location" ~ param,
                            func == "var-p-skew" ~ (param*10-1)/(param*10+(10-param*10)-2),
                            func== "var-p-width" ~ 0.5))%>%
    ungroup()
}

e3_gam_params <- read_parquet("data-raw/sim/results/gam_params_e3.parquet")
e3_gam_params <- full_join(ref_metadata_e3, e3_gam_params, by="sample_id")

e3_lextrema_results_me <- read_parquet("data-raw/sim/results/lextrema_results_me_e3.parquet")
e3_lextrema_results_me <- full_join(ref_metadata_e3, e3_lextrema_results_me, by="sample_id")

e3_lextrema_results_gratia <- read_parquet("data-raw/sim/results/lextrema_results_gr_e3.parquet")
e3_lextrema_results_gratia <- full_join(ref_metadata_e3, e3_lextrema_results_gratia, by="sample_id")

e3_peaktest_results <- read_parquet("data-raw/sim/results/peaktest_results_e3.parquet")
 
e3_summary <- get_results(peak_test = e3_peaktest_results,
                          lextr_me =e3_lextrema_results_me, 
                          lextr_gr =  e3_lextrema_results_gratia, 
                          gam_params = e3_gam_params, 
                          func_type_p = c("var-p-location", "var-p-skew","var-p-width" ),
                          func_type_np = NULL,
                          me = TRUE)

saveRDS(object = e3_summary, file = "data-raw/sim/analy_results/e3_summary.RDS")

e3_coverage_long <- tidyr::pivot_longer(data=e3_summary$coverage, cols = c("coverage_me", "coverage_me_max", "coverage_gr", "coverage_gr_max"), names_to = "cov_type", values_to = "coverage")

#boundary maxes are skewed to the bound???
ggplot(data=e3_coverage_long)+
  geom_line(aes(x=param, y=coverage, colour=cov_type))+
  geom_hline(aes(yintercept = 0.95), colour="firebrick", linetype=2)+
  facet_grid(dup~func)+
  theme_bw()

#boundary maxes are skewed to the bound??? Example:
gam_e3_5 <- gam(y~s(x, bs= "ad", m=3), method = "REML", data=filter(sim_dat_e3, sample_id ==5))
lextrema_e3_5 <- lextremagam::quantify_lextrema(gam_e3_5, var = "x", deriv_method = "gratia")
plot_e3_5 <- lextremagam::plot_lextrema(lextrema_e3_5, plot_deriv = TRUE, show_segs = TRUE, show_segs_deriv = TRUE)
plot_e3_5$model_plot+
  geom_point(data=filter(sim_dat_e3, sample_id ==5), aes(x=x, y=y))+
  geom_line(data=filter(sim_dat_e3, sample_id ==5), aes(x=x, y=y_true))
```

#Experiment 4
```{r}
setwd("~/Documents/Pedersen2023/Peaks/lextremagam")

if(!exists("ref_metadata_e4")){
sim_dat_e4 <- read_parquet("data-raw/sim/data/sim_dat_e4.parquet")
  #adding reference data
  ref_metadata_e4 <- sim_dat_e4%>%
    group_by(func, param, rep, error, dup, scenario_id)%>%
    summarize(sample_id=first(sample_id))%>%
    mutate(peak = NA)%>%
    ungroup()
}

e4_gam_params <- read_parquet("data-raw/sim/results/gam_params_e4.parquet")
e4_gam_params <- full_join(ref_metadata_e4, e4_gam_params, by="sample_id")

e4_lextrema_results_gratia <- read_parquet("data-raw/sim/results/lextrema_results_gr_e4.parquet")
e4_lextrema_results_gratia <- full_join(ref_metadata_e4, e4_lextrema_results_gratia, by="sample_id")

e4_peaktest_results <- read_parquet("data-raw/sim/results/peaktest_results_e4.parquet")
 
e4_summary <- get_results(peak_test = e4_peaktest_results,
                          lextr_me =e4_lextrema_results_me, 
                          lextr_gr =  e4_lextrema_results_gratia, 
                          gam_params = e4_gam_params, 
                          func_type_p = NULL,
                          func_type_np = c("var-curvature", "var-location", "var-scale"), 
                          me = FALSE)

saveRDS(object = e4_summary, file = "data-raw/sim/analy_results/e4_summary.RDS")

e4_fperror_long <- tidyr::pivot_longer(data=e4_summary$fperror, cols = c("quad", "rprop", "pr_gr"), names_to = "fpe_type", values_to = "fperror")

ggplot(data=e4_fperror_long)+
  geom_line(aes(x=param, y=fperror, colour=fpe_type))+
  geom_hline(aes(yintercept = 0.05), colour="firebrick", linetype=2)+
  facet_grid(dup~func)+
  theme_bw()
```

#experiment 1-4 TPRS default
```{r}
setwd("~/Documents/Pedersen2023/Peaks/lextremagam")

if(!exists("ref_metadata_e1")){
  sim_dat_e1 <- read_parquet("data-raw/sim/data/sim_dat_e1.parquet")
  #adding reference data
  ref_metadata_e1 <- sim_dat_e1%>%
    group_by(func, param, rep, error, dup, scenario_id)%>%
    summarize(sample_id=first(sample_id))%>%
    mutate(peak = case_when(func=="norm"~param,
                            func == "linear"~NA))%>%
    ungroup()
}

e1_gam_params_tprs <- read_parquet("data-raw/sim/results/gam_params_e1_tprs.parquet")
e1_gam_params_tprs <- full_join(ref_metadata_e1, e1_gam_params_tprs, by="sample_id")

e1_lextrema_results_gratia_tprs <- read_parquet("data-raw/sim/results/lextrema_results_gr_e1_tprs.parquet")
e1_lextrema_results_gratia_tprs <- full_join(ref_metadata_e1, e1_lextrema_results_gratia_tprs, by="sample_id")

e1_peaktest_results_tprs <- read_parquet("data-raw/sim/results/peaktest_results_e1_tprs.parquet")

e1_summary_tprs <- get_results(peak_test = e1_peaktest_results_tprs,
                          lextr_me =e1_lextrema_results_gratia_tprs,
                          lextr_gr =  e1_lextrema_results_gratia_tprs,
                          gam_params = e1_gam_params_tprs,
                          func_type_p = "norm",
                          func_type_np = "linear",
                          me = FALSE)
#exp 2
if(!exists("ref_metadata_e2")) {
  sim_dat_e2 <- read_parquet("data-raw/sim/data/sim_dat_e2.parquet")
  #adding reference data
  ref_metadata_e2 <- sim_dat_e2%>%
    group_by(func, param, rep, error, dup, scenario_id)%>%
    summarize(sample_id=first(sample_id))%>%
    mutate(peak = case_when(func=="norm"~param,
                            func == "linear"~NA))%>%
    ungroup()
}
e2_gam_params_tprs <- read_parquet("data-raw/sim/results/gam_params_e2_tprs.parquet")
e2_gam_params_tprs <- full_join(ref_metadata_e2, e2_gam_params_tprs, by="sample_id")

e2_lextrema_results_gratia_tprs <- read_parquet("data-raw/sim/results/lextrema_results_gr_e2_tprs.parquet")
e2_lextrema_results_gratia_tprs <- full_join(ref_metadata_e2, e2_lextrema_results_gratia_tprs, by="sample_id")

e2_peaktest_results_tprs <- read_parquet("data-raw/sim/results/peaktest_results_e2_tprs.parquet")
 
e2_summary_tprs <- get_results(peak_test = e2_peaktest_results_tprs,
                          lextr_me =e2_lextrema_results_gratia_tprs, 
                          lextr_gr =  e2_lextrema_results_gratia_tprs, 
                          gam_params = e2_gam_params_tprs, 
                          func_type_p = "norm", 
                          func_type_np = "linear",
                          me = FALSE)
# exp 3
if(!exists("ref_metadata_e3")){
  sim_dat_e3 <- read_parquet("data-raw/sim/data/sim_dat_e3.parquet")
  #adding reference data
  ref_metadata_e3 <- sim_dat_e3%>%
    group_by(func, param, rep, error, dup, scenario_id)%>%
    summarize(sample_id=first(sample_id))%>%
    mutate(peak = case_when(func == "var-p-location" ~ param,
                            func == "var-p-skew" ~ (param*10-1)/(param*10+(10-param*10)-2),
                            func== "var-p-width" ~ 0.5))%>%
    ungroup()
}
e3_gam_params_tprs <- read_parquet("data-raw/sim/results/gam_params_e3_tprs.parquet")
e3_gam_params_tprs <- full_join(ref_metadata_e3, e3_gam_params_tprs, by="sample_id")

e3_lextrema_results_gratia_tprs <- read_parquet("data-raw/sim/results/lextrema_results_gr_e3_tprs.parquet")
e3_lextrema_results_gratia_tprs <- full_join(ref_metadata_e3, e3_lextrema_results_gratia_tprs, by="sample_id")

e3_peaktest_results_tprs <- read_parquet("data-raw/sim/results/peaktest_results_e3_tprs.parquet")
 
e3_summary_tprs <- get_results(peak_test = e3_peaktest_results_tprs,
                          lextr_me =e3_lextrema_results_gratia_tprs, 
                          lextr_gr =  e3_lextrema_results_gratia_tprs, 
                          gam_params = e3_gam_params_tprs, 
                          func_type_p = c("var-p-location", "var-p-skew","var-p-width" ),
                          func_type_np = NULL,
                          me = FALSE)

#exp4
if(!exists("ref_metadata_e4")){
  sim_dat_e4 <- read_parquet("data-raw/sim/data/sim_dat_e4.parquet")
  #adding reference data
  ref_metadata_e4 <- sim_dat_e4%>%
    group_by(func, param, rep, error, dup, scenario_id)%>%
    summarize(sample_id=first(sample_id))%>%
    mutate(peak = NA)%>%
    ungroup()
}

e4_gam_params_tprs <- read_parquet("data-raw/sim/results/gam_params_e4_tprs.parquet")
e4_gam_params_tprs <- full_join(ref_metadata_e4, e4_gam_params_tprs, by="sample_id")

e4_lextrema_results_gratia_tprs <- read_parquet("data-raw/sim/results/lextrema_results_gr_e4_tprs.parquet")
e4_lextrema_results_gratia_tprs <- full_join(ref_metadata_e4, e4_lextrema_results_gratia_tprs, by="sample_id")

e4_peaktest_results_tprs <- read_parquet("data-raw/sim/results/peaktest_results_e4_tprs.parquet")
 
e4_summary_tprs <- get_results(peak_test = e4_peaktest_results_tprs,
                          lextr_me =e4_lextrema_results_gratia_tprs, 
                          lextr_gr =  e4_lextrema_results_gratia_tprs, 
                          gam_params = e4_gam_params_tprs, 
                          func_type_p = NULL,
                          func_type_np = c("var-curvature", "var-location", "var-scale"),
                          me = FALSE)

e1_4_summary_tprs <- list(
  e1 = e1_summary_tprs,
  e2 = e2_summary_tprs, 
  e3 = e3_summary_tprs,
  e4 = e4_summary_tprs
)


setwd("~/Documents/Pedersen2023/Peaks/lextremagam")

saveRDS(e1_4_summary_tprs, "data-raw/sim/analy_results/e1_4_summary_tprs.RDS")
```

#experiment 1-4 adjalpha tprs
```{r}
setwd("~/Documents/Pedersen2023/Peaks/lextremagam")

if(!exists("ref_metadata_e1")){
  sim_dat_e1 <- read_parquet("data-raw/sim/data/sim_dat_e1.parquet")
  #adding reference data
  ref_metadata_e1 <- sim_dat_e1%>%
    group_by(func, param, rep, error, dup, scenario_id)%>%
    summarize(sample_id=first(sample_id))%>%
    mutate(peak = case_when(func=="norm"~param,
                            func == "linear"~NA))%>%
    ungroup()
}
e1_gam_params_adjalpha <- read_parquet("data-raw/sim/results/gam_params_e1_adjalpha.parquet")
e1_gam_params_adjalpha <- full_join(ref_metadata_e1, e1_gam_params_adjalpha, by="sample_id")

e1_lextrema_results_gratia_adjalpha <- read_parquet("data-raw/sim/results/lextrema_results_gr_e1_adjalpha.parquet")
e1_lextrema_results_gratia_adjalpha <- full_join(ref_metadata_e1, e1_lextrema_results_gratia_adjalpha, by="sample_id")

e1_peaktest_results_adjalpha <- read_parquet("data-raw/sim/results/peaktest_results_e1_adjalpha.parquet")

e1_summary_adjalpha <- get_results(peak_test = e1_peaktest_results_adjalpha,
                          lextr_me =e1_lextrema_results_gratia_adjalpha,
                          lextr_gr =  e1_lextrema_results_gratia_adjalpha,
                          gam_params = e1_gam_params_adjalpha,
                          func_type_p = "norm",
                          func_type_np = "linear",
                          me = FALSE)

if(!exists("ref_metadata_e2")){
sim_dat_e2 <- read_parquet("data-raw/sim/data/sim_dat_e2.parquet")
  #adding reference data
  ref_metadata_e2 <- sim_dat_e2%>%
    group_by(func, param, rep, error, dup, scenario_id)%>%
    summarize(sample_id=first(sample_id))%>%
        mutate(peak = case_when(func=="norm"~param,
                            func == "linear"~NA))%>%
    ungroup()
}

e2_gam_params_adjalpha <- read_parquet("data-raw/sim/results/gam_params_e2_adjalpha.parquet")
e2_gam_params_adjalpha <- full_join(ref_metadata_e2, e2_gam_params_adjalpha, by="sample_id")

e2_lextrema_results_gratia_adjalpha <- read_parquet("data-raw/sim/results/lextrema_results_gr_e2_adjalpha.parquet")
e2_lextrema_results_gratia_adjalpha <- full_join(ref_metadata_e2, e2_lextrema_results_gratia_adjalpha, by="sample_id")

e2_peaktest_results_adjalpha <- read_parquet("data-raw/sim/results/peaktest_results_e2_adjalpha.parquet")
 
e2_summary_adjalpha <- get_results(peak_test = e2_peaktest_results_adjalpha,
                          lextr_me =e2_lextrema_results_gratia_adjalpha, 
                          lextr_gr =  e2_lextrema_results_gratia_adjalpha, 
                          gam_params = e2_gam_params_adjalpha, 
                          func_type_p = "norm", 
                          func_type_np = "linear",
                          me = FALSE)

#exp 3
if(!exists("ref_metadata_e3")){
  sim_dat_e3 <- read_parquet("data-raw/sim/data/sim_dat_e3.parquet")
  #adding reference data
  ref_metadata_e3 <- sim_dat_e3%>%
    group_by(func, param, rep, error, dup, scenario_id)%>%
    summarize(sample_id=first(sample_id))%>%
    mutate(peak = case_when(func == "var-p-location" ~ param,
                            func == "var-p-skew" ~ (param*10-1)/(param*10+(10-param*10)-2),
                            func== "var-p-width" ~ 0.5))%>%
    ungroup()
}
e3_gam_params_adjalpha <- read_parquet("data-raw/sim/results/gam_params_e3_adjalpha.parquet")
e3_gam_params_adjalpha <- full_join(ref_metadata_e3, e3_gam_params_adjalpha, by="sample_id")

e3_lextrema_results_gratia_adjalpha <- read_parquet("data-raw/sim/results/lextrema_results_gr_e3_adjalpha.parquet")
e3_lextrema_results_gratia_adjalpha <- full_join(ref_metadata_e3, e3_lextrema_results_gratia_adjalpha, by="sample_id")

e3_peaktest_results_adjalpha <- read_parquet("data-raw/sim/results/peaktest_results_e3_adjalpha.parquet")
 
e3_summary_adjalpha <- get_results(peak_test = e3_peaktest_results_adjalpha,
                          lextr_me =e3_lextrema_results_gratia_adjalpha, 
                          lextr_gr =  e3_lextrema_results_gratia_adjalpha, 
                          gam_params = e3_gam_params_adjalpha, 
                          func_type_p = c("var-p-location", "var-p-skew","var-p-width" ),
                          func_type_np = NULL,
                          me = FALSE)

#exp 4
if(!exists("ref_metadata_e4")){
  sim_dat_e4 <- read_parquet("data-raw/sim/data/sim_dat_e4.parquet")
  #adding reference data
  ref_metadata_e4 <- sim_dat_e4%>%
    group_by(func, param, rep, error, dup, scenario_id)%>%
    summarize(sample_id=first(sample_id))%>%
    mutate(peak = NA)%>%
    ungroup()
}

e4_gam_params_adjalpha <- read_parquet("data-raw/sim/results/gam_params_e4_adjalpha.parquet")
e4_gam_params_adjalpha <- full_join(ref_metadata_e4, e4_gam_params_adjalpha, by="sample_id")

e4_lextrema_results_gratia_adjalpha <- read_parquet("data-raw/sim/results/lextrema_results_gr_e4_adjalpha.parquet")
e4_lextrema_results_gratia_adjalpha <- full_join(ref_metadata_e4, e4_lextrema_results_gratia_adjalpha, by="sample_id")

e4_peaktest_results_adjalpha <- read_parquet("data-raw/sim/results/peaktest_results_e4_adjalpha.parquet")
 
e4_summary_adjalpha <- get_results(peak_test = e4_peaktest_results_adjalpha,
                          lextr_me =e4_lextrema_results_gratia_adjalpha, 
                          lextr_gr =  e4_lextrema_results_gratia_adjalpha, 
                          gam_params = e4_gam_params_adjalpha, 
                          func_type_p = NULL,
                          func_type_np = c("var-curvature", "var-location", "var-scale"),
                          me = FALSE)

e1_4_summary_adjalpha <- list(
  e1 = e1_summary_adjalpha,
  e2 = e2_summary_adjalpha, 
  e3 = e3_summary_adjalpha,
  e4 = e4_summary_adjalpha
)

setwd("~/Documents/Pedersen2023/Peaks/lextremagam")

saveRDS(e1_4_summary_adjalpha, "data-raw/sim/analy_results/e1_4_summary_adjalpha.RDS")

e3_coverage_long <- tidyr::pivot_longer(data=e3_summary$coverage, cols = c("coverage_me", "coverage_me_max", "coverage_gr", "coverage_gr_max"), names_to = "cov_type", values_to = "coverage")

pdf("e1_4_tprs_adj_plots.pdf")
#POWER ####
ggplot(data=tidyr::pivot_longer(e1_4_summary_adjalpha$e1$power, cols = c("quad", "rprop", "pr_gr"), names_to = "method", values_to = "power"))+
  geom_point(aes(x=dup, y=power, colour=method))+
  geom_line(aes(x=dup, y=power, colour=method))

ggplot(data=tidyr::pivot_longer(e1_4_summary_adjalpha$e2$power, cols = c("quad", "rprop", "pr_gr"), names_to = "method", values_to = "power"))+
  geom_point(aes(x=error, y=power, colour=method))+
  geom_line(aes(x=error, y=power, colour=method))

ggplot(data=filter(tidyr::pivot_longer(e1_4_summary_adjalpha$e3$power, cols = c("quad", "rprop", "pr_gr"), names_to = "method", values_to = "power"), func!="var-p-width"))+
  geom_point(aes(x=peak, y=power, colour=method))+
  geom_line(aes(x=peak, y=power, colour=method))+
  facet_grid(dup~func)
  geom_point(aes(x=param, y=power, colour=method))+
  geom_line(aes(x=param, y=power, colour=method))+
  facet_grid(dup~func)

#TYPE I ERROR ####
ggplot(data=tidyr::pivot_longer(e1_4_summary_adjalpha$e1$fperror, cols = c("quad", "rprop", "pr_gr"), names_to = "method", values_to = "fperror"))+
  geom_point(aes(x=dup, y=fperror, colour=method))+
  geom_line(aes(x=dup, y=fperror, colour=method))+
  geom_hline(aes(yintercept=0.05), linetype=2)

ggplot(data=tidyr::pivot_longer(e1_4_summary_adjalpha$e2$fperror, cols = c("quad", "rprop", "pr_gr"), names_to = "method", values_to = "fperror"))+
  geom_point(aes(x=error, y=fperror, colour=method))+
  geom_line(aes(x=error, y=fperror, colour=method))+
  geom_hline(aes(yintercept=0.05), linetype=2)

ggplot(data=tidyr::pivot_longer(e1_4_summary_adjalpha$e4$fperror, cols = c("quad", "rprop", "pr_gr"), names_to = "method", values_to = "fperror"))+
  geom_point(aes(x=param, y=fperror, colour=method))+
  geom_line(aes(x=param, y=fperror, colour=method))+
  geom_hline(aes(yintercept=0.05), linetype=2)+
  facet_grid(dup~func)

# COVERAGE ####
ggplot(data=e1_4_summary_adjalpha_ad$e1$coverage)+
  geom_point(aes(x=dup, y=coverage_gr))+
  geom_line(aes(x=dup, y=coverage_gr))+
  geom_hline(aes(yintercept=0.95), linetype=2)

ggplot(data=e1_4_summary_adjalpha$e2$coverage)+
  geom_point(aes(x=error, y=coverage_gr))+
  geom_line(aes(x=error, y=coverage_gr))+
  geom_hline(aes(yintercept=0.95), linetype=2)

ggplot(data=filter(e1_4_summary_adjalpha$e3$coverage, func!="var-p-width"))+
  geom_point(aes(x=peak, y=coverage_gr, colour=as.factor(dup)))+
  geom_line(aes(x=peak, y=coverage_gr, colour=as.factor(dup)))+
  geom_hline(aes(yintercept=0.95), linetype=2)+
  facet_wrap(~func)

ggplot(data=filter(e1_4_summary_adjalpha$e3$coverage, func=="var-p-width"))+
  geom_point(aes(x=param, y=coverage_gr, colour=as.factor(dup)))+
  geom_line(aes(x=param, y=coverage_gr, colour=as.factor(dup)))+
  geom_hline(aes(yintercept=0.95), linetype=2)+
  facet_wrap(~func)

#PRECISION ####
ggplot(data=e1_4_summary_adjalpha$e1$precision)+
  geom_point(aes(x=dup, y=width_avg_gr))+
  geom_line(aes(x=dup, y=width_avg_gr))+
  geom_ribbon(aes(x = dup, ymin=width_avg_gr-width_sd_gr, ymax=width_avg_gr+width_sd_gr), alpha=0.2)

ggplot(data=e1_4_summary_adjalpha$e2$precision)+
  geom_point(aes(x=error, y=width_avg_gr))+
  geom_line(aes(x=error, y=width_avg_gr))+
  geom_ribbon(aes(x = error, ymin=width_avg_gr-width_sd_gr, ymax=width_avg_gr+width_sd_gr), alpha=0.2)

ggplot(data=filter(e1_4_summary_adjalpha$e3$precision, func !="var-p-width"))+
  geom_point(aes(x=peak, y=width_avg_gr, colour=as.factor(dup)))+
  geom_line(aes(x=peak, y=width_avg_gr, colour=as.factor(dup)))+
  geom_ribbon(aes(x = peak, ymin=width_avg_gr-width_sd_gr, ymax=width_avg_gr+width_sd_gr, fill=as.factor(dup)), alpha=0)+
  facet_wrap(~func)

ggplot(data=filter(e1_4_summary_adjalpha$e3$precision, func =="var-p-width"))+
  geom_point(aes(x=param, y=width_avg_gr, colour=as.factor(dup)))+
  geom_line(aes(x=param, y=width_avg_gr, colour=as.factor(dup)))+
  geom_ribbon(aes(x = param, ymin=width_avg_gr-width_sd_gr, ymax=width_avg_gr+width_sd_gr, fill=as.factor(dup)), alpha=0)+
  facet_wrap(~func)

# BIAS ####
ggplot(data=filter(e1_4_summary_adjalpha$e1$bias, func== "norm"))+
  geom_point(aes(x=dup, y=bias_avg_gr))+
  geom_line(aes(x=dup, y=bias_avg_gr))+
  geom_ribbon(aes(x = dup, ymin=bias_avg_gr-bias_sd_gr, ymax=bias_avg_gr+bias_sd_gr), alpha=0.2)+
  geom_hline(aes( yintercept=0), linetype=2)

ggplot(data=filter(e1_4_summary_adjalpha$e2$bias, func== "norm"))+
  geom_point(aes(x=error, y=bias_avg_gr))+
  geom_line(aes(x=error, y=bias_avg_gr))+
  geom_ribbon(aes(x = error, ymin=bias_avg_gr-bias_sd_gr, ymax=bias_avg_gr+bias_sd_gr), alpha=0.2)+
  geom_hline(aes(yintercept=0), linetype=2)

ggplot(data=filter(e1_4_summary_adjalpha$e3$bias, func!= "var-p-width"))+
  geom_point(aes(x=peak, y=bias_avg_gr, colour=as.factor(dup)))+
  geom_line(aes(x=peak, y=bias_avg_gr, colour=as.factor(dup)))+
  geom_ribbon(aes(x = peak, ymin=bias_avg_gr-bias_sd_gr, ymax=bias_avg_gr+bias_sd_gr, fill=as.factor(dup)), alpha=0.1)+
  geom_hline(aes( yintercept=0), linetype=2)+
facet_wrap(~func)

ggplot(data=filter(e1_4_summary_adjalpha$e3$bias, func== "var-p-width"))+
  geom_point(aes(x=param, y=bias_avg_gr, colour=as.factor(dup)))+
  geom_line(aes(x=param, y=bias_avg_gr, colour=as.factor(dup)))+
  geom_ribbon(aes(x = param, ymin=bias_avg_gr-bias_sd_gr, ymax=bias_avg_gr+bias_sd_gr, fill=as.factor(dup)), alpha=0.1)+
  geom_hline(aes( yintercept=0), linetype=2)+
facet_wrap(~func)

dev.off()
```
#experiment 1-4 adjalpha ad
```{r}
setwd("~/Documents/Pedersen2023/Peaks/lextremagam")

if(!exists("ref_metadata_e1")){
  sim_dat_e1 <- read_parquet("data-raw/sim/data/sim_dat_e1.parquet")
  #adding reference data
  ref_metadata_e1 <- sim_dat_e1%>%
    group_by(func, param, rep, error, dup, scenario_id)%>%
    summarize(sample_id=first(sample_id))%>%
    mutate(peak = case_when(func=="norm"~param,
                            func == "linear"~NA))%>%
    ungroup()
}
e1_gam_params_adjalpha_ad <- read_parquet("data-raw/sim/results/gam_params_e1_adjalpha_ad.parquet")
e1_gam_params_adjalpha_ad <- full_join(ref_metadata_e1, e1_gam_params_adjalpha_ad, by="sample_id")

e1_lextrema_results_gratia_adjalpha_ad <- read_parquet("data-raw/sim/results/lextrema_results_gr_e1_adjalpha_ad.parquet")
e1_lextrema_results_gratia_adjalpha_ad <- full_join(ref_metadata_e1, e1_lextrema_results_gratia_adjalpha_ad, by="sample_id")

e1_peaktest_results_adjalpha_ad <- read_parquet("data-raw/sim/results/peaktest_results_e1_adjalpha_ad.parquet")

e1_summary_adjalpha_ad <- get_results(peak_test = e1_peaktest_results_adjalpha_ad,
                          lextr_me =e1_lextrema_results_gratia_adjalpha_ad,
                          lextr_gr =  e1_lextrema_results_gratia_adjalpha_ad,
                          gam_params = e1_gam_params_adjalpha_ad,
                          func_type_p = "norm",
                          func_type_np = "linear",
                          me = FALSE)

#Exp 2
if(!exists("ref_metadata_e2")){
sim_dat_e2 <- read_parquet("data-raw/sim/data/sim_dat_e2.parquet")
  #adding reference data
  ref_metadata_e2 <- sim_dat_e2%>%
    group_by(func, param, rep, error, dup, scenario_id)%>%
    summarize(sample_id=first(sample_id))%>%
        mutate(peak = case_when(func=="norm"~param,
                            func == "linear"~NA))%>%
    ungroup()
}

e2_gam_params_adjalpha_ad <- read_parquet("data-raw/sim/results/gam_params_e2_adjalpha_ad.parquet")
e2_gam_params_adjalpha_ad <- full_join(ref_metadata_e2, e2_gam_params_adjalpha_ad, by="sample_id")

e2_lextrema_results_gratia_adjalpha_ad <- read_parquet("data-raw/sim/results/lextrema_results_gr_e2_adjalpha_ad.parquet")
e2_lextrema_results_gratia_adjalpha_ad <- full_join(ref_metadata_e2, e2_lextrema_results_gratia_adjalpha_ad, by="sample_id")

e2_peaktest_results_adjalpha_ad <- read_parquet("data-raw/sim/results/peaktest_results_e2_adjalpha_ad.parquet")
 
e2_summary_adjalpha_ad <- get_results(peak_test = e2_peaktest_results_adjalpha_ad,
                          lextr_me =e2_lextrema_results_gratia_adjalpha_ad, 
                          lextr_gr =  e2_lextrema_results_gratia_adjalpha_ad, 
                          gam_params = e2_gam_params_adjalpha_ad, 
                          func_type_p = "norm", 
                          func_type_np = "linear",
                          me = FALSE)

#exp 3
if(!exists("ref_metadata_e3")){
  sim_dat_e3 <- read_parquet("data-raw/sim/data/sim_dat_e3.parquet")
  #adding reference data
  ref_metadata_e3 <- sim_dat_e3%>%
    group_by(func, param, rep, error, dup, scenario_id)%>%
    summarize(sample_id=first(sample_id))%>%
    mutate(peak = case_when(func == "var-p-location" ~ param,
                            func == "var-p-skew" ~ (param*10-1)/(param*10+(10-param*10)-2),
                            func== "var-p-width" ~ 0.5))%>%
    ungroup()
}
e3_gam_params_adjalpha_ad <- read_parquet("data-raw/sim/results/gam_params_e3_adjalpha_ad.parquet")
e3_gam_params_adjalpha_ad <- full_join(ref_metadata_e3, e3_gam_params_adjalpha_ad, by="sample_id")

e3_lextrema_results_gratia_adjalpha_ad <- read_parquet("data-raw/sim/results/lextrema_results_gr_e3_adjalpha_ad.parquet")
e3_lextrema_results_gratia_adjalpha_ad <- full_join(ref_metadata_e3, e3_lextrema_results_gratia_adjalpha_ad, by="sample_id")

e3_peaktest_results_adjalpha_ad <- read_parquet("data-raw/sim/results/peaktest_results_e3_adjalpha_ad.parquet")
 
e3_summary_adjalpha_ad <- get_results(peak_test = e3_peaktest_results_adjalpha_ad,
                          lextr_me =e3_lextrema_results_gratia_adjalpha_ad, 
                          lextr_gr =  e3_lextrema_results_gratia_adjalpha_ad, 
                          gam_params = e3_gam_params_adjalpha_ad, 
                          func_type_p = c("var-p-location", "var-p-skew","var-p-width" ),
                          func_type_np = NULL,
                          me = FALSE)

#exp 4
setwd("~/Documents/Pedersen2023/Peaks/lextremagam")
if(!exists("ref_metadata_e4")){
  sim_dat_e4 <- read_parquet("data-raw/sim/data/sim_dat_e4.parquet")
  #adding reference data
  ref_metadata_e4 <- sim_dat_e4%>%
    group_by(func, param, rep, error, dup, scenario_id)%>%
    summarize(sample_id=first(sample_id))%>%
    mutate(peak = NA)%>%
    ungroup()
}

e4_gam_params_adjalpha_ad <- read_parquet("data-raw/sim/results/gam_params_e4_adjalpha_ad.parquet")
e4_gam_params_adjalpha_ad <- full_join(ref_metadata_e4, e4_gam_params_adjalpha_ad, by="sample_id")

e4_lextrema_results_gratia_adjalpha_ad <- read_parquet("data-raw/sim/results/lextrema_results_gr_e4_adjalpha_ad.parquet")
e4_lextrema_results_gratia_adjalpha_ad <- full_join(ref_metadata_e4, e4_lextrema_results_gratia_adjalpha_ad, by="sample_id")

e4_peaktest_results_adjalpha_ad <- read_parquet("data-raw/sim/results/peaktest_results_e4_adjalpha_ad.parquet")
 
e4_summary_adjalpha_ad <- get_results(peak_test = e4_peaktest_results_adjalpha_ad,
                          lextr_me =e4_lextrema_results_gratia_adjalpha_ad, 
                          lextr_gr =  e4_lextrema_results_gratia_adjalpha_ad, 
                          gam_params = e4_gam_params_adjalpha, 
                          func_type_p = NULL,
                          func_type_np = c("var-curvature", "var-location", "var-scale"),
                          me = FALSE)

e1_4_summary_adjalpha_ad <- list(
  e1 = e1_summary_adjalpha_ad,
  e2 = e2_summary_adjalpha_ad, 
  e3 = e3_summary_adjalpha_ad,
  e4 = e4_summary_adjalpha_ad
)


setwd("~/Documents/Pedersen2023/Peaks/lextremagam")

saveRDS(e1_4_summary_adjalpha_ad, "data-raw/sim/analy_results/e1_4_summary_adjalpha_ad.RDS")

pdf("e1_4_tprs_adj_ad_plots.pdf")
#POWER ####
ggplot(data=tidyr::pivot_longer(e1_4_summary_adjalpha_ad$e1$power, cols = c("quad", "rprop", "pr_gr"), names_to = "method", values_to = "power"))+
  geom_point(aes(x=dup, y=power, colour=method))+
  geom_line(aes(x=dup, y=power, colour=method))

ggplot(data=tidyr::pivot_longer(e1_4_summary_adjalpha_ad$e2$power, cols = c("quad", "rprop", "pr_gr"), names_to = "method", values_to = "power"))+
  geom_point(aes(x=error, y=power, colour=method))+
  geom_line(aes(x=error, y=power, colour=method))

ggplot(data=filter(tidyr::pivot_longer(e1_4_summary_adjalpha_ad$e3$power, cols = c("quad", "rprop", "pr_gr"), names_to = "method", values_to = "power"), func!="var-p-width"))+
  geom_point(aes(x=peak, y=power, colour=method))+
  geom_line(aes(x=peak, y=power, colour=method))+
  facet_grid(dup~func)
ggplot(data=filter(tidyr::pivot_longer(e1_4_summary_adjalpha_ad$e3$power, cols = c("quad", "rprop", "pr_gr"), names_to = "method", values_to = "power"), func=="var-p-width"))+
  geom_point(aes(x=param, y=power, colour=method))+
  geom_line(aes(x=param, y=power, colour=method))+
  facet_grid(dup~func)

#TYPE I ERROR ####
ggplot(data=tidyr::pivot_longer(e1_4_summary_adjalpha_ad$e1$fperror, cols = c("quad", "rprop", "pr_gr"), names_to = "method", values_to = "fperror"))+
  geom_point(aes(x=dup, y=fperror, colour=method))+
  geom_line(aes(x=dup, y=fperror, colour=method))+
  geom_hline(aes(yintercept=0.05), linetype=2)

ggplot(data=tidyr::pivot_longer(e1_4_summary_adjalpha_ad$e2$fperror, cols = c("quad", "rprop", "pr_gr"), names_to = "method", values_to = "fperror"))+
  geom_point(aes(x=error, y=fperror, colour=method))+
  geom_line(aes(x=error, y=fperror, colour=method))+
  geom_hline(aes(yintercept=0.05), linetype=2)

ggplot(data=tidyr::pivot_longer(e1_4_summary_adjalpha_ad$e4$fperror, cols = c("quad", "rprop", "pr_gr"), names_to = "method", values_to = "fperror"))+
  geom_point(aes(x=param, y=fperror, colour=method))+
  geom_line(aes(x=param, y=fperror, colour=method))+
  geom_hline(aes(yintercept=0.05), linetype=2)+
  facet_grid(dup~func)

# COVERAGE ####
ggplot(data=e1_4_summary_adjalpha_ad$e1$coverage)+
  geom_point(aes(x=dup, y=coverage_gr))+
  geom_line(aes(x=dup, y=coverage_gr))+
  geom_hline(aes(yintercept=0.95), linetype=2)

ggplot(data=e1_4_summary_adjalpha_ad$e2$coverage)+
  geom_point(aes(x=error, y=coverage_gr))+
  geom_line(aes(x=error, y=coverage_gr))+
  geom_hline(aes(yintercept=0.95), linetype=2)

ggplot(data=filter(e1_4_summary_adjalpha_ad$e3$coverage, func!="var-p-width"))+
  geom_point(aes(x=peak, y=coverage_gr, colour=as.factor(dup)))+
  geom_line(aes(x=peak, y=coverage_gr, colour=as.factor(dup)))+
  geom_hline(aes(yintercept=0.95), linetype=2)+
  facet_wrap(~func)

ggplot(data=filter(e1_4_summary_adjalpha_ad$e3$coverage, func=="var-p-width"))+
  geom_point(aes(x=param, y=coverage_gr, colour=as.factor(dup)))+
  geom_line(aes(x=param, y=coverage_gr, colour=as.factor(dup)))+
  geom_hline(aes(yintercept=0.95), linetype=2)+
  facet_wrap(~func)

#PRECISION ####
ggplot(data=e1_4_summary_adjalpha_ad$e1$precision)+
  geom_point(aes(x=dup, y=width_avg_gr))+
  geom_line(aes(x=dup, y=width_avg_gr))+
  geom_ribbon(aes(x = dup, ymin=width_avg_gr-width_sd_gr, ymax=width_avg_gr+width_sd_gr), alpha=0.2)

ggplot(data=e1_4_summary_adjalpha_ad$e2$precision)+
  geom_point(aes(x=error, y=width_avg_gr))+
  geom_line(aes(x=error, y=width_avg_gr))+
  geom_ribbon(aes(x = error, ymin=width_avg_gr-width_sd_gr, ymax=width_avg_gr+width_sd_gr), alpha=0.2)

ggplot(data=filter(e1_4_summary_adjalpha_ad$e3$precision, func !="var-p-width"))+
  geom_point(aes(x=peak, y=width_avg_gr, colour=as.factor(dup)))+
  geom_line(aes(x=peak, y=width_avg_gr, colour=as.factor(dup)))+
  geom_ribbon(aes(x = peak, ymin=width_avg_gr-width_sd_gr, ymax=width_avg_gr+width_sd_gr, fill=as.factor(dup)), alpha=0)+
  facet_wrap(~func)

ggplot(data=filter(e1_4_summary_adjalpha_ad$e3$precision, func =="var-p-width"))+
  geom_point(aes(x=param, y=width_avg_gr, colour=as.factor(dup)))+
  geom_line(aes(x=param, y=width_avg_gr, colour=as.factor(dup)))+
  geom_ribbon(aes(x = param, ymin=width_avg_gr-width_sd_gr, ymax=width_avg_gr+width_sd_gr, fill=as.factor(dup)), alpha=0)+
  facet_wrap(~func)

# BIAS ####
ggplot(data=filter(bias_all_data$e1_3_bias_adjalpha_ad$e1_bias_adjalpha_ad, func== "norm"))+
  geom_point(aes(x=dup, y=bias_avg_gr_max))+
  geom_line(aes(x=dup, y=bias_avg_gr_max))+
  geom_ribbon(aes(x = dup, ymin=bias_avg_gr_max-bias_sd_gr_max, ymax=bias_avg_gr_max+bias_sd_gr_max), alpha=0.2)+
  geom_hline(aes( yintercept=0), linetype=2)

ggplot(data=filter(bias_all_data$e1_3_bias_adjalpha_ad$e2_bias_adjalpha_ad, func== "norm"))+
  geom_point(aes(x=error, y=bias_avg_gr_max))+
  geom_line(aes(x=error, y=bias_avg_gr_max))+
  geom_ribbon(aes(x = error, ymin=bias_avg_gr_max-bias_sd_gr_max, ymax=bias_avg_gr_max+bias_sd_gr_max), alpha=0.2)+
  geom_hline(aes(yintercept=0), linetype=2)

ggplot(data=filter(bias_all_data$e1_3_bias_adjalpha_ad$e3_bias_adjalpha_ad, func!= "var-p-width"))+
  geom_point(aes(x=peak, y=bias_avg_gr_max, colour=as.factor(dup)))+
  geom_line(aes(x=peak, y=bias_avg_gr_max, colour=as.factor(dup)))+
  geom_ribbon(aes(x = peak, ymin=bias_avg_gr_max-bias_sd_gr_max, ymax=bias_avg_gr_max+bias_sd_gr_max, fill=as.factor(dup)), alpha=0.1)+
  geom_hline(aes( yintercept=0), linetype=2)+
facet_wrap(~func)

ggplot(data=filter(bias_all_data$e1_3_bias_adjalpha_ad$e3_bias_adjalpha_ad, func== "var-p-width"))+
  geom_point(aes(x=param, y=bias_avg_gr_max, colour=as.factor(dup)))+
  geom_line(aes(x=param, y=bias_avg_gr_max, colour=as.factor(dup)))+
  geom_ribbon(aes(x = param, ymin=bias_avg_gr_max-bias_sd_gr_max, ymax=bias_avg_gr_max+bias_sd_gr_max, fill=as.factor(dup)), alpha=0.1)+
  geom_hline(aes( yintercept=0), linetype=2)+
facet_wrap(~func)

dev.off()
```

# Analyze new way of doing bias for all ####
```{r}

setwd("~/Documents/Pedersen2023/Peaks/lextremagam")
#import all data ####

n_gam_params <- c(names(list(mget(ls(pattern = "e1_gam_params")))[[1]]), 
                names(list(mget(ls(pattern = "e2_gam_params")))[[1]]),
                names(list(mget(ls(pattern = "e3_gam_params")))[[1]]))

n_lextrema_results_me <- c(names(list(mget(ls(pattern = "e1_lextrema_results_me")))[[1]]),
                         names(list(mget(ls(pattern = "e2_lextrema_results_me")))[[1]]),
                         names(list(mget(ls(pattern = "e3_lextrema_results_me")))[[1]]))

n_lextrema_results_gr <- c(names(list(mget(ls(pattern = "e1_lextrema_results_gr")))[[1]]), 
                         names(list(mget(ls(pattern = "e2_lextrema_results_gr")))[[1]]),
                         names(list(mget(ls(pattern = "e3_lextrema_results_gr")))[[1]]))

n_peaktest_results <- c(names(list(mget(ls(pattern = "e1_peaktest_results")))[[1]]),
                        names(list(mget(ls(pattern = "e2_peaktest_results")))[[1]]),
                        names(list(mget(ls(pattern = "e3_peaktest_results")))[[1]]))

if(length(n_gam_params)<12|
   length(n_lextrema_results_me)<3|
   length(n_lextrema_results_gr)<12|
   length(n_peaktest_results)<12){
e1_gam_params <- read_parquet("data-raw/sim/results/gam_params_e1.parquet")
e1_gam_params <- full_join(ref_metadata_e1, e1_gam_params, by="sample_id")

e1_lextrema_results_me <- read_parquet("data-raw/sim/results/lextrema_results_me_e1.parquet")
e1_lextrema_results_me <- full_join(ref_metadata_e1, e1_lextrema_results_me, by="sample_id")

e1_lextrema_results_gratia <- read_parquet("data-raw/sim/results/lextrema_results_gr_e1.parquet")
e1_lextrema_results_gratia <- full_join(ref_metadata_e1, e1_lextrema_results_gratia, by="sample_id")

e1_peaktest_results <- read_parquet("data-raw/sim/results/peaktest_results_e1.parquet")
 
e2_gam_params <- read_parquet("data-raw/sim/results/gam_params_e2.parquet")
e2_gam_params <- full_join(ref_metadata_e2, e2_gam_params, by="sample_id")

e2_lextrema_results_me <- read_parquet("data-raw/sim/results/lextrema_results_me_e2.parquet")
e2_lextrema_results_me <- full_join(ref_metadata_e2, e2_lextrema_results_me, by="sample_id")
e2_lextrema_results_me$feature[which(is.na(e2_lextrema_results_me$feature))] <- "notrend"

e2_lextrema_results_gratia <- read_parquet("data-raw/sim/results/lextrema_results_gr_e2.parquet")
e2_lextrema_results_gratia <- full_join(ref_metadata_e2, e2_lextrema_results_gratia, by="sample_id")
e2_lextrema_results_gratia$feature[which(is.na(e2_lextrema_results_gratia$feature))] <- "notrend"

e2_peaktest_results <- read_parquet("data-raw/sim/results/peaktest_results_e2.parquet")

e3_gam_params <- read_parquet("data-raw/sim/results/gam_params_e3.parquet")
e3_gam_params <- full_join(ref_metadata_e3, e3_gam_params, by="sample_id")

e3_lextrema_results_me <- read_parquet("data-raw/sim/results/lextrema_results_me_e3.parquet")
e3_lextrema_results_me <- full_join(ref_metadata_e3, e3_lextrema_results_me, by="sample_id")

e3_lextrema_results_gratia <- read_parquet("data-raw/sim/results/lextrema_results_gr_e3.parquet")
e3_lextrema_results_gratia <- full_join(ref_metadata_e3, e3_lextrema_results_gratia, by="sample_id")

e3_peaktest_results <- read_parquet("data-raw/sim/results/peaktest_results_e3.parquet")

##tprs ####
e1_gam_params_tprs <- read_parquet("data-raw/sim/results/gam_params_e1_tprs.parquet")
e1_gam_params_tprs <- full_join(ref_metadata_e1, e1_gam_params_tprs, by="sample_id")

e1_lextrema_results_gratia_tprs <- read_parquet("data-raw/sim/results/lextrema_results_gr_e1_tprs.parquet")
e1_lextrema_results_gratia_tprs <- full_join(ref_metadata_e1, e1_lextrema_results_gratia_tprs, by="sample_id")

e1_peaktest_results_tprs <- read_parquet("data-raw/sim/results/peaktest_results_e1_tprs.parquet")

e2_gam_params_tprs <- read_parquet("data-raw/sim/results/gam_params_e2_tprs.parquet")
e2_gam_params_tprs <- full_join(ref_metadata_e2, e2_gam_params_tprs, by="sample_id")

e2_lextrema_results_gratia_tprs <- read_parquet("data-raw/sim/results/lextrema_results_gr_e2_tprs.parquet")
e2_lextrema_results_gratia_tprs <- full_join(ref_metadata_e2, e2_lextrema_results_gratia_tprs, by="sample_id")

e2_peaktest_results_tprs <- read_parquet("data-raw/sim/results/peaktest_results_e2_tprs.parquet")

e3_gam_params_tprs <- read_parquet("data-raw/sim/results/gam_params_e3_tprs.parquet")
e3_gam_params_tprs <- full_join(ref_metadata_e3, e3_gam_params_tprs, by="sample_id")

e3_lextrema_results_gratia_tprs <- read_parquet("data-raw/sim/results/lextrema_results_gr_e3_tprs.parquet")
e3_lextrema_results_gratia_tprs <- full_join(ref_metadata_e3, e3_lextrema_results_gratia_tprs, by="sample_id")

e3_peaktest_results_tprs <- read_parquet("data-raw/sim/results/peaktest_results_e3_tprs.parquet")

##Adj ad

e1_gam_params_adjalpha_ad <- read_parquet("data-raw/sim/results/gam_params_e1_adjalpha_ad.parquet")
e1_gam_params_adjalpha_ad <- full_join(ref_metadata_e1, e1_gam_params_adjalpha_ad, by="sample_id")

e1_lextrema_results_gratia_adjalpha_ad <- read_parquet("data-raw/sim/results/lextrema_results_gr_e1_adjalpha_ad.parquet")
e1_lextrema_results_gratia_adjalpha_ad <- full_join(ref_metadata_e1, e1_lextrema_results_gratia_adjalpha_ad, by="sample_id")

e1_peaktest_results_adjalpha_ad <- read_parquet("data-raw/sim/results/peaktest_results_e1_adjalpha_ad.parquet")

e2_gam_params_adjalpha_ad <- read_parquet("data-raw/sim/results/gam_params_e2_adjalpha_ad.parquet")
e2_gam_params_adjalpha_ad <- full_join(ref_metadata_e2, e2_gam_params_adjalpha_ad, by="sample_id")

e2_lextrema_results_gratia_adjalpha_ad <- read_parquet("data-raw/sim/results/lextrema_results_gr_e2_adjalpha_ad.parquet")
e2_lextrema_results_gratia_adjalpha_ad <- full_join(ref_metadata_e2, e2_lextrema_results_gratia_adjalpha_ad, by="sample_id")

e2_peaktest_results_adjalpha_ad <- read_parquet("data-raw/sim/results/peaktest_results_e2_adjalpha_ad.parquet")

e3_gam_params_adjalpha_ad <- read_parquet("data-raw/sim/results/gam_params_e3_adjalpha_ad.parquet")
e3_gam_params_adjalpha_ad <- full_join(ref_metadata_e3, e3_gam_params_adjalpha_ad, by="sample_id")

e3_lextrema_results_gratia_adjalpha_ad <- read_parquet("data-raw/sim/results/lextrema_results_gr_e3_adjalpha_ad.parquet")
e3_lextrema_results_gratia_adjalpha_ad <- full_join(ref_metadata_e3, e3_lextrema_results_gratia_adjalpha_ad, by="sample_id")

e3_peaktest_results_adjalpha_ad <- read_parquet("data-raw/sim/results/peaktest_results_e3_adjalpha_ad.parquet")
}

#Exp 1 ad unadjusted ####
e1_bias <- get_bias2(lextr_me = e1_lextrema_results_me, 
                     lextr_gr = e1_lextrema_results_gratia, 
                     func_type = "norm", me = FALSE)

#Exp 2 ad unadjusted ####
e2_bias <- get_bias2(lextr_me = e2_lextrema_results_me,
                    lextr_gr = e2_lextrema_results_gratia, 
                    func_type = "norm", 
                    me = FALSE)

# Exp 3 ad unadjusted ####
e3_bias <- get_bias2(lextr_me = e3_lextrema_results_me,
                    lextr_gr = e3_lextrema_results_gratia, 
                    func_type = c("var-p-location", "var-p-skew","var-p-width" ), 
                    me = FALSE)

# Exp 1-3 TRPS Adj ####
e1_bias_tprs <- get_bias2(lextr_me = e1_lextrema_results_gratia_tprs,
                    lextr_gr = e1_lextrema_results_gratia_tprs, 
                    func_type = "norm", 
                    me = FALSE)
#exp 2
e2_bias_tprs <- get_bias2(lextr_me = e2_lextrema_results_gratia_tprs,
                    lextr_gr = e2_lextrema_results_gratia_tprs, 
                    func_type = "norm", 
                    me = FALSE)
  
# exp 3
e3_bias_tprs <-get_bias2(lextr_me = e3_lextrema_results_gratia_tprs,
                    lextr_gr = e3_lextrema_results_gratia_tprs, 
                    func_type = c("var-p-location", "var-p-skew","var-p-width" ), 
                    me = FALSE)

# Exp 1-4 tprs adjusted ####
e1_bias_adjalpha <- get_bias2(lextr_me = e1_lextrema_results_gratia_adjalpha,
                                   lextr_gr = e1_lextrema_results_gratia_adjalpha, 
                                   func_type = "norm", 
                                   me = FALSE)
  
#Exp 2
e2_bias_adjalpha <- get_bias2(lextr_me = e2_lextrema_results_gratia_adjalpha,
                                   lextr_gr = e2_lextrema_results_gratia_adjalpha, 
                                   func_type = "norm", 
                                   me = FALSE)

#exp 3
e3_bias_adjalpha <- get_bias2(lextr_me = e3_lextrema_results_gratia_adjalpha,
                                   lextr_gr = e3_lextrema_results_gratia_adjalpha, 
                                   func_type = c("var-p-location", "var-p-skew","var-p-width" ), 
                                   me = FALSE)

# Exp 1-4 ad adjusted ####
e1_bias_adjalpha_ad <- get_bias2(lextr_me = e1_lextrema_results_gratia_adjalpha_ad,
                                   lextr_gr = e1_lextrema_results_gratia_adjalpha_ad, 
                                   func_type = "norm", 
                                   me = FALSE)
  
#Exp 2
e2_bias_adjalpha_ad <- get_bias2(lextr_me = e2_lextrema_results_gratia_adjalpha_ad,
                                   lextr_gr = e2_lextrema_results_gratia_adjalpha_ad, 
                                   func_type = "norm", 
                                   me = FALSE)

#exp 3
e3_bias_adjalpha_ad <- get_bias2(lextr_me = e3_lextrema_results_gratia_adjalpha_ad,
                                   lextr_gr = e3_lextrema_results_gratia_adjalpha_ad, 
                                   func_type = c("var-p-location", "var-p-skew","var-p-width" ), 
                                   me = FALSE)

#export data

bias_all_data <- list(e1_3_bias_ad = list(e1_bias = e1_bias,
                                          e2_bias= e2_bias,
                                          e3_bias= e3_bias), 
                      e1_3_bias_tprs = list(e1_bias_tprs= e1_bias_tprs,
                                                e2_bias_tprs=e2_bias_tprs,
                                                e3_bias_tprs=e3_bias_tprs),
                      e1_3_bias_adjalpha = list(e1_bias_adjalpha=e1_bias_adjalpha,
                                                e2_bias_adjalpha=e2_bias_adjalpha,
                                                e3_bias_adjalpha=e3_bias_adjalpha), 
                      e1_3_bias_adjalpha_ad= list(e1_bias_adjalpha_ad=e1_bias_adjalpha_ad, 
                                                  e2_bias_adjalpha_ad=e2_bias_adjalpha_ad, 
                                                  e3_bias_adjalpha_ad=e3_bias_adjalpha_ad))

saveRDS(file = "data-raw/sim/analy_results/bias_all_data.RDS", object = bias_all_data)
```

#Analyse TRPS and adaptive together ####
```{r}
#merge adaptive and TPRS adjusted results
#pivot_longer

pivot_long_no_me <- function(x){
  x$power <- tidyr::pivot_longer(x$power, 
                                 cols = c("quad", "rprop", "pr_gr"), 
                                 names_to = "method", values_to = "power")
  x$fperror <- tidyr::pivot_longer(x$fperror, 
                                   cols = c("quad", "rprop", "pr_gr"), 
                                   names_to = "method", values_to = "power")
  x$coverage <- tidyr::pivot_longer(x$coverage, 
                                    cols = c("coverage_gr", "coverage_gr_max"), 
                                    names_to = "method", values_to = "power")

  return(x)
}
e1_4_summary_adjalpha_long <- lapply(e1_4_summary_adjalpha, FUN = pivot_long_no_me)
e1_4_summary_adjalpha_long$power <- rbind(e1_4_summary_adjalpha_long$e1$power,
                                          e1_4_summary_adjalpha_long$e2$power,
                                          e1_4_summary_adjalpha_long$e3$power,
                                          e1_4_summary_adjalpha_long$e4$power)
e1_4_summary_adjalpha_long$fperror <- rbind(e1_4_summary_adjalpha_long$e1$fperror,
                                          e1_4_summary_adjalpha_long$e2$fperror,
                                          e1_4_summary_adjalpha_long$e3$fperror,
                                          e1_4_summary_adjalpha_long$e4$fperror)
e1_4_summary_adjalpha_long$coverage <- rbind(e1_4_summary_adjalpha_long$e1$coverage,
                                          e1_4_summary_adjalpha_long$e2$coverage,
                                          e1_4_summary_adjalpha_long$e3$coverage,
                                          e1_4_summary_adjalpha_long$e4$coverage)
e1_4_summary_adjalpha_long$precision <- rbind(e1_4_summary_adjalpha_long$e1$precision,
                                          e1_4_summary_adjalpha_long$e2$precision,
                                          e1_4_summary_adjalpha_long$e3$precision,
                                          e1_4_summary_adjalpha_long$e4$precision)
e1_4_summary_adjalpha_long$bias <- rbind(e1_4_summary_adjalpha_long$e1$bias,
                                          e1_4_summary_adjalpha_long$e2$bias,
                                          e1_4_summary_adjalpha_long$e3$bias,
                                          e1_4_summary_adjalpha_long$e4$bias)
e1_4_summary_adjalpha_ad_long <- lapply(e1_4_summary_adjalpha_ad, FUN = pivot_long_no_me)
e1_4_summary_adjalpha_ad_long$power <- rbind(e1_4_summary_adjalpha_ad_long$e1$power,
                                          e1_4_summary_adjalpha_ad_long$e2$power,
                                          e1_4_summary_adjalpha_ad_long$e3$power,
                                          e1_4_summary_adjalpha_ad_long$e4$power)
e1_4_summary_adjalpha_ad_long$fperror <- rbind(e1_4_summary_adjalpha_ad_long$e1$fperror,
                                          e1_4_summary_adjalpha_ad_long$e2$fperror,
                                          e1_4_summary_adjalpha_ad_long$e3$fperror,
                                          e1_4_summary_adjalpha_ad_long$e4$fperror)
e1_4_summary_adjalpha_ad_long$coverage <- rbind(e1_4_summary_adjalpha_ad_long$e1$coverage,
                                          e1_4_summary_adjalpha_ad_long$e2$coverage,
                                          e1_4_summary_adjalpha_ad_long$e3$coverage,
                                          e1_4_summary_adjalpha_ad_long$e4$coverage)
e1_4_summary_adjalpha_ad_long$precision <- rbind(e1_4_summary_adjalpha_ad_long$e1$precision,
                                          e1_4_summary_adjalpha_ad_long$e2$precision,
                                          e1_4_summary_adjalpha_ad_long$e3$precision,
                                          e1_4_summary_adjalpha_ad_long$e4$precision)
e1_4_summary_adjalpha_ad_long$bias <- rbind(e1_4_summary_adjalpha_ad_long$e1$bias,
                                          e1_4_summary_adjalpha_ad_long$e2$bias,
                                          e1_4_summary_adjalpha_ad_long$e3$bias,
                                          e1_4_summary_adjalpha_ad_long$e4$bias)


results_adj_alpha <- list()
results_adj_alpha$power <- bind_rows(e1_4_summary_adjalpha_long$power, 
                                 e1_4_summary_adjalpha_ad_long$power, .id="source")
results_adj_alpha$fperror <- bind_rows(e1_4_summary_adjalpha_long$fperror,
                                   e1_4_summary_adjalpha_ad_long$fperror, .id="source")
results_adj_alpha$coverage <- bind_rows(e1_4_summary_adjalpha_long$coverage,
                                    e1_4_summary_adjalpha_ad_long$coverage, .id="source")
results_adj_alpha$precision <- bind_rows(e1_4_summary_adjalpha_long$precision, 
                          e1_4_summary_adjalpha_ad_long$precision, .id="source")
results_adj_alpha$bias <- bind_rows(e1_4_summary_adjalpha_long$bias, 
                          e1_4_summary_adjalpha_ad_long$bias, .id="source")

```



```{r}

```


```{r}

```


```{r}

```


```{r}
# 
# #peaktest results analysis ####
#   ##false-positive####
#   e1_peaktest_results <- e1_peaktest_results%>%mutate(peaked = case_when(func=="linear" ~ 0,
#                                                                          func=="norm" ~ 1))
#   #TP, TN, FP, FN
#   e1_peaktest_det <- e1_peaktest_results%>%
#     group_by(scenario_id, func, param, error, dup)%>%
#     summarize(quad = sum(quad_u==peaked)/n(),
#               rmax = sum(rmax_u==peaked)/n(),
#               rmed = sum(rmed_u==peaked)/n(),
#               rprop = sum(rprop_u==peaked)/n(),
#               lines3 = sum(lines3_u==peaked)/n())%>%
#     ungroup()
#   
#   #False-positive error rate
#   e1_peaktest_fpr <- e1_peaktest_det%>%
#     filter(func=="linear")%>%
#     mutate(quad = 1-quad,
#            rmax = 1-rmax,
#            rmed = 1-rmed,
#            rprop = 1-rprop,
#            lines3 = 1-lines3)
#   
#   #Power rate
#   e1_peaktest_pr <- e1_peaktest_det%>%
#     filter(func=="norm")
# 
# #assess proportion of peaks detected via the methods. ####
#   #marginaleffect
#   lextrema_me_det <-  e1_lextrema_results_me%>%
#     group_by(scenario_id, func, param, rep, error, dup, sample_id)%>%
#     summarize(peak_det_l = any(feature == "local_max"),
#               peak_det_g = any(feature %in% c("local_max", "boundary_max")))%>%
#     ungroup()%>%
#     group_by(scenario_id, func, param, error, dup, )%>%
#     summarize(peak_det_l = sum(peak_det_l)/n(),
#               peak_det_g = sum(peak_det_g)/n(),
#               n=n())%>%
#     ungroup()
#   
#   lextrema_me_fpr <- lextrema_me_det%>%
#     filter(func=="linear")
#   
#   lextrema_me_pr <- lextrema_me_det%>%
#     filter(func=="norm")
#   
#   samples_global_det <- unique(e1_lextrema_results_me$sample_id[which(e1_lextrema_results_me$feature %in% c("local_max", "boundary_max"))])
#   samples_local_det <- unique(e1_lextrema_results_me$sample_id[which(e1_lextrema_results_me$feature == "local_max")])
#   
#   lextrema_me_peak_capture_global <- e1_lextrema_results_me%>%
#     filter(func=="norm"  & 
#              sample_id %in% samples_global_det & 
#              feature %in% c("local_max", "boundary_max"))%>%
#     rowwise()%>%
#     mutate(g_capture = (param>=x_start & param<=x_end),
#            dist_x_start = abs(param-x_start),
#            dist_x_end = abs(param-x_end),
#            dist_ci = min(dist_x_start,dist_x_end))%>%
#     ungroup()%>%
#     group_by(scenario_id, func, rep, param, error, dup, sample_id)%>%
#     summarize(g_peak_captured = sum(g_capture),
#               dist_ci = min(dist_ci))%>%
#     ungroup()
#   
#   lextrema_me_peak_coverage_global <-lextrema_me_peak_capture_global%>%
#     group_by(scenario_id, func, param, error, dup)%>%
#     summarize(coverage= sum(g_peak_captured)/n())%>%
#     ungroup()
# 
#   lextrema_me_peak_capture_local <- e1_lextrema_results_me%>%
#     filter(func=="norm"  & 
#              sample_id %in% samples_local_det & 
#              feature %in% c("local_max"))%>%
#     rowwise()%>%
#     mutate(g_capture = (param>=x_start & param<=x_end),
#            dist_x_start = (param-x_start),
#            dist_x_end = (param-x_end),
#            dist_ci = ifelse(abs(dist_x_start)<=abs(dist_x_end),
#                             dist_x_start, dist_x_end))%>%
#     ungroup()%>%
#     group_by(scenario_id, func, rep, param, error, dup, sample_id)%>%
#     summarize(l_peak_captured = sum(g_capture),
#               dist_ci = min(dist_ci))%>%
#     ungroup()
#   
#   lextrema_me_peak_coverage_local <-lextrema_me_peak_capture_local%>%
#     group_by(scenario_id, func, param, error, dup)%>%
#     summarize(coverage= sum(l_peak_captured)/n())%>%
#     ungroup()
# 
#   lextrema_me_bias_global <- lextrema_me_peak_capture_global %>%
#     mutate(dist_ci = case_when(g_peak_captured ==1 ~ 0, 
#                                g_peak_captured == 0 ~ dist_ci))%>%
#     group_by(scenario_id, func, error, dup)%>%
#     summarize(mean_dist_ci = mean(dist_ci),
#               sd_dist_ci = sd(dist_ci), 
#               n=n())%>%
#     ungroup()
#   
#   #weird bias artefact cause: boundary max at the start edge
#   View(filter(e1_lextrema_results_me, sample_id %in% weird_dist_ci, feature %in% c("local_max", "boundary_max")))
#   
#   lextrema_me_bias_local <- lextrema_me_peak_capture_local %>%
#     mutate(dist_ci = case_when(l_peak_captured ==1 ~ 0, 
#                                l_peak_captured == 0 ~ dist_ci))%>%
#     group_by(scenario_id, func, error, dup)%>%
#     summarize(mean_dist_ci = mean(dist_ci),
#               sd_dist_ci = sd(dist_ci), 
#               n=n())%>%
#     ungroup()
#   
#   lextrema_me_precision_global <- e1_lextrema_results_me%>%
#     filter(func=="norm", feature %in% c("local_max", "boundary_max"))%>%
#     mutate(width= x_end-x_start)%>%
#     group_by(func, param, rep, error, dup, scenario_id, sample_id)%>%
#     summarize(sum_width= sum(width),
#               n_seg = n())%>%
#     ungroup()%>%
#     group_by(func, param, error, dup, scenario_id)%>%
#     summarize(width_avg = mean(sum_width),
#               width_sd = sd(sum_width),
#               n_2plseg = sum(n_seg>=2),
#               n=n())%>%
#     ungroup()
#     
#   
#   ##Gratia ####
#    lextrema_gr_det <-  e1_lextrema_results_gratia%>%
#     group_by(scenario_id, func, param, rep, error, dup, sample_id)%>%
#     summarize(peak_det_l = any(feature %in% c("local_max")),
#               peak_det_g = any(feature %in% c("local_max", "boundary_max")))%>%
#     ungroup()%>%
#     group_by(scenario_id, func, param, error, dup, )%>%
#     summarize(peak_det_l = sum(peak_det_l)/n(),
#               peak_det_g = sum(peak_det_g)/n(),
#               n=n())%>%
#     ungroup()
#   
#   lextrema_gr_fpr <- lextrema_gr_det%>%
#     filter(func=="linear")
#   
#   lextrema_gr_pr <- lextrema_gr_det%>%
#     filter(func=="norm")
#   
#   samples_global_det <- unique(e1_lextrema_results_gratia$sample_id[which(e1_lextrema_results_gratia$feature %in% c("local_max", "boundary_max"))])
#   samples_local_det <- unique(e1_lextrema_results_gratia$sample_id[which(e1_lextrema_results_gratia$feature == "local_max")])
#   
#   lextrema_gr_peak_capture_global <- e1_lextrema_results_gratia%>%
#     filter(func=="norm"  & 
#              sample_id %in% samples_global_det & 
#              feature %in% c("local_max", "boundary_max"))%>%
#     rowwise()%>%
#     mutate(g_capture = (param>=x_start & param<=x_end),
#            dist_x_start = abs(param-x_start),
#            dist_x_end = abs(param-x_end),
#            dist_ci = min(dist_x_start,dist_x_end))%>%
#     ungroup()%>%
#     group_by(scenario_id, func, rep, param, error, dup, sample_id)%>%
#     summarize(g_peak_captured = sum(g_capture),
#               dist_ci = min(dist_ci))%>%
#     ungroup()
#   
#   lextrema_gr_peak_coverage_global <-lextrema_gr_peak_capture_global%>%
#     group_by(scenario_id, func, param, error, dup)%>%
#     summarize(coverage= sum(g_peak_captured)/n())%>%
#     ungroup()
# 
#   lextrema_gr_peak_capture_local <- e1_lextrema_results_gratia%>%
#     filter(func=="norm"  & 
#              sample_id %in% samples_local_det & 
#              feature %in% c("local_max"))%>%
#     rowwise()%>%
#     mutate(g_capture = (param>=x_start & param<=x_end),
#            dist_x_start = (param-x_start),
#            dist_x_end = (param-x_end),
#            dist_ci = ifelse(abs(dist_x_start)<=abs(dist_x_end),
#                             dist_x_start, dist_x_end))%>%
#     ungroup()%>%
#     group_by(scenario_id, func, rep, param, error, dup, sample_id)%>%
#     summarize(l_peak_captured = sum(g_capture),
#               dist_ci = min(dist_ci))%>%
#     ungroup()
#   
#   lextrema_gr_peak_coverage_local <-lextrema_gr_peak_capture_local%>%
#     group_by(scenario_id, func, param, error, dup)%>%
#     summarize(coverage= sum(l_peak_captured)/n())%>%
#     ungroup()
# 
#   lextrema_gr_bias_global <- lextrema_gr_peak_capture_global %>%
#     mutate(dist_ci = case_when(g_peak_captured ==1 ~ 0, 
#                                g_peak_captured == 0 ~ dist_ci))%>%
#     group_by(scenario_id, func, error, dup)%>%
#     summarize(mean_dist_ci = mean(dist_ci),
#               sd_dist_ci = sd(dist_ci), 
#               n=n())%>%
#     ungroup()
#   
#   lextrema_gr_bias_local <- lextrema_gr_peak_capture_local %>%
#     mutate(dist_ci = case_when(l_peak_captured ==1 ~ 0, 
#                                l_peak_captured == 0 ~ dist_ci))%>%
#     group_by(scenario_id, func, error, dup)%>%
#     summarize(mean_dist_ci = mean(dist_ci),
#               sd_dist_ci = sd(dist_ci), 
#               n=n())%>%
#     ungroup()
#     
#   
#   
#   
#   
#   
#   
#   
#   
#   
#   
#     
#     n_lextrema_me <- e1_lextrema_results%>%
#       group_by(func, param, rep, error, dup, scenario_id, sample_id)%>%
#       summarize(n_local_max = sum(feature=="local_max"),
#                n_local_min = sum(feature=="local_min"),
#                n_boundary_max = sum(feature=="boundary_max"),
#                n_boundary_min = sum(feature=="boundary_max"),
#                n_extrema = sum(feature %in% c("local_max", "local_min", "boundary_max", "boundary_min")),
#                extrema_detected = n_extrema!=0,
#                local_max_detected = n_local_max !=0)%>%
#       ungroup()
#     
#     lextrema_me_power <- n_lextrema_me%>%
#       filter(func == "norm")%>%
#       group_by(func, param, error, dup, scenario_id)%>%
#       summarize(n_extrema_detected = sum(extrema_detected),
#                 prop_extrema_detected = sum(extrema_detected)/n(),
#                 n_local_max_detected = sum(local_max_detected),
#                 prop_local_max_detected = sum(local_max_detected)/n())%>%
#       ungroup()
#     
#     coverage_me <- e1_lextrema_results%>%
#       filter(func=="norm", feature %in% c("boundary_max", "local_max"))%>%
#       
#       group_by(func, param, error, dup, scenario_id)%>%
#       summarize(n_samples = n_distinct(sample_id),
#                 capture_local = sum(param>x_start & param<x_end &feature %in% "local_max"),
#                 rate_local = capture_local/n_samples,
#                 capture = sum(param>x_start & param<x_end &feature %in% c("local_max", "boundary_max")),
#                 rate = capture/n_samples)%>%
#       ungroup
#     
#     lextrema_me_false_pos <- n_lextrema_me%>%
#       filter(func == "linear")%>%
#       group_by(func, param, error, dup, scenario_id)%>%
#       summarize(n_extrema_detected = sum(extrema_detected),
#                 prop_extrema_detected = sum(extrema_detected)/n(),
#                 n_local_max_detected = sum(local_max_detected),
#                 prop_local_max_detected = sum(local_max_detected)/n())%>%
#       ungroup()
#     
#   #gratia
#     n_lextrema_gratia <- e1_lextrema_results_gratia%>%
#        group_by(func, param, rep, error, dup, scenario_id, sample_id)%>%
#       summarize(n_local_max = sum(feature=="local_max"),
#                n_local_min = sum(feature=="local_min"),
#                n_boundary_max = sum(feature=="boundary_max"),
#                n_boundary_min = sum(feature=="boundary_max"),
#                n_extrema = sum(feature %in% c("local_max", "local_min", "boundary_max", "boundary_min")),
#                extrema_detected = n_extrema!=0,
#                local_max_detected = n_local_max !=0)%>%
#       ungroup()
#     
#     lextrema_gratia_power <- n_lextrema_gratia%>%
#       filter(func == "norm")%>%
#       group_by(func, param, error, dup, scenario_id)%>%
#       summarize(n_extrema_detected = sum(extrema_detected),
#                 prop_extrema_detected = sum(extrema_detected)/n(),
#                 n_local_max_detected = sum(local_max_detected),
#                 prop_local_max_detected = sum(local_max_detected)/n())%>%
#       ungroup()
#     
#     coverage_gratia <- e1_lextrema_results_gratia%>%
#       filter(func=="norm", feature %in% c("boundary_max", "local_max"))%>%
#       
#       group_by(func, param, error, dup, scenario_id)%>%
#       summarize(n_samples = n_distinct(sample_id),
#                 capture_local = sum(param>x_start & param<x_end &feature %in% "local_max"),
#                 rate_local = capture_local/n_samples,
#                 capture = sum(param>x_start & param<x_end &feature %in% c("local_max", "boundary_max")),
#                 rate = capture/n_samples)%>%
#       ungroup
#     
#     lextrema_gratia_false_pos <- n_lextrema_gratia%>%
#       filter(func == "linear")%>%
#       group_by(func, param, error, dup, scenario_id)%>%
#       summarize(n_extrema_detected = sum(extrema_detected),
#                 prop_extrema_detected = sum(extrema_detected)/n(),
#                 n_local_max_detected = sum(local_max_detected),
#                 prop_local_max_detected = sum(local_max_detected)/n())%>%
#       ungroup()
#   #simonoshn
# #assess if lextremagam found a peak
# #assess if lextremagam peak includes true value


```

