---
title: "S04-analyze_real_data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{S04-analyze_real_data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(lextremagam)
library(mgcv)
library(gratia)
knitr::opts_knit$set(root.dir = "~/Documents/Pedersen2023/Peaks/lextremagam")
```

# Import Data ####
```{r}
HalpernSpies1995_w1 <- read.csv("data-raw/real_data/CLEAN_HalpernSpies1995_Fig1d_w1.csv")
plot(HalpernSpies1995_w1$heterogeneity~HalpernSpies1995_w1$t_disturbance)

HalpernSpies1995_w2 <- read.csv("data-raw/real_data/CLEAN_HalpernSpies1995_Fig1d_w2.csv")
plot(HalpernSpies1995_w2$heterogeneity~HalpernSpies1995_w2$t_disturbance)

WilsonKeddy1988 <- read.csv("data-raw/real_data/CLEAN_WilsonKeddy1988.csv")
WilsonKeddy1988$ln_somc_perc <- log(WilsonKeddy1988$somc_perc)
plot(WilsonKeddy1988$n_sp~WilsonKeddy1988$ln_somc_perc)

bishop2021 <- read.csv("data-raw/real_data/NBP1701_diatom_growth_rate_data_Award1543245_20220627.csv")
plot(bishop2021$specific_growth_rate~bishop2021$temperature)
```
# Halpern and Spies ####
```{r}
#quadratic test
hs1995w1_quad <- lextremagam:::peaktest_quad(x = HalpernSpies1995_w1$t_disturbance, 
                                             y = HalpernSpies1995_w1$heterogeneity)
#Two-lines test
hs1995w1_tl <- lextremagam:::peaktest_twolines(x = HalpernSpies1995_w1$t_disturbance, 
                                             y = HalpernSpies1995_w1$heterogeneity)
#lextremagam
hs1195w1_gam <- gam(heterogeneity~s(t_disturbance, bs="ad", k=10, m=3), method="REML", data=HalpernSpies1995_w1)
hs1195w1_lextr <- lextremagam::quantify_lextrema2(mod = hs1195w1_gam, 
                                                 var = "t_disturbance", 
                                                 step_size = 0.02, 
                                                 conf_level = 0.95, 
                                                 deriv_method = "gratia")

hs1195w1_lextr_plot <- plot_lextrema(quant_segments = hs1195w1_lextr, plot_deriv = TRUE)


```

```{r}
#quadratic test
wk1988_quad <- lextremagam:::peaktest_quad(x = WilsonKeddy1988$ln_somc_perc, 
                                             y = WilsonKeddy1988$n_sp)
#Two-lines test
wk1988_tl <- lextremagam:::peaktest_twolines(x = WilsonKeddy1988$ln_somc_perc, 
                                             y = WilsonKeddy1988$n_sp)
#lextremagam
wk1988_gam <- gam(n_sp~s(ln_somc_perc, bs="ad", k=20, m=3), method="REML", data=WilsonKeddy1988, family=nb)
wk1988_lextr <- lextremagam::quantify_lextrema2(mod = wk1988_gam, 
                                                 var = "ln_somc_perc", 
                                                 conf_level = 0.95, 
                                                step_size = 0.0002,
                                                 deriv_method = "gratia")

wk1988_lextr_plot <- plot_lextrema(quant_segments = wk1988_lextr, plot_deriv = TRUE)
```

```{r}

bishop2021
#quadratic test
b2021_quad <- lextremagam:::peaktest_quad(x = bishop2021$temperature, 
                                             y = bishop2021$specific_growth_rate)
#Two-lines test
b2021_tl <- lextremagam:::peaktest_twolines(x = bishop2021$temperature, 
                                             y = bishop2021$specific_growth_rate)
#lextremagam
bishop2021$species <- as.factor(bishop2021$species)
b2021_gam <- gam(specific_growth_rate~s(temperature, by=species, k=5), method="REML", data=bishop2021)

b2021_lextr_ac <- lextremagam::quantify_lextrema2(mod = b2021_gam, 
                                               var = "temperature", 
                                               step_size=0.015,
                                               conf_level = 0.95, 
                                               deriv_method = "gratia", 
                                               multivariate = TRUE, 
                                               smooth = "s(temperature):speciesActinocyclus curvatulus")

b2021_lextr_plot <- plot_lextrema(quant_segments = b2021_lextr_ac, plot_deriv = TRUE)


```

```{r}

```
